### ISSUE TITLE
Flattening breaks instance overriding if constants have multiple names

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#1032]
See https://github.com/informalsystems/quint/pull/1023#issuecomment-1625468080

If a module with constants is imported and/or exported with a qualifier, and the exported thing is then instatiated, the instance cannot be compiled because only one set of constants is overwritten.

**Comment by konnov** [comment]
I think this issue really boils down to avoiding duplication of definitions that have the same id

**Comment by bugarela** [comment]
Fixed by the new flattener
