### ISSUE TITLE
Name resolution can fail in the simulator depending on operator order

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1035]
I found a strange edge case in which name resolution of an imported operator incorrectly fails, but only if the operators are imported in a specific order and the main module is loaded in a specific way :woman_shrugging: 

This issue is light on details because I've opened a draft PR with a failing integration test in #1036.

**Comment by bugarela** [comment]
Very strange! Thanks for the detailed example

**Comment by shonfeder** [comment]
Thanks for taking a look! This is very strange indeed. I’m sorry I wasn’t able to derive a more minimal reproduction, but it seems so sensitive to the exact order of defs that every little thing I changed would avoid the problem!
