### ISSUE TITLE
Records operators don't type check argument arity correctly

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1054]
Looks like we don't have the right arity checks in place for the record operators. Here are some examples:

```
>>> r
{ a: 1 }
>>> r.field("a", 1)
static analysis error: error: [QNT000] Expected 3 arguments, got 2

>>> {a: 1}.fieldNames()
Set("a")
>>> {a: 1}.fieldNames(1, 2, 3)
Set()
>>> {a: 1}.with("a", 2, 4, 5, 6)
static analysis error: error: [QNT000] Expected 6 arguments, got 3

>>> Tup(1, 2).item(1, 2, 3)
static analysis error: error: [QNT000] Expected 4 arguments, got 2
```

This is because the constraints that guard correct operator signatures are not applied if we use a "specialConstraint": https://github.com/informalsystems/quint/blob/123a237513bbc92d7b629566a5573f3b076f66ab/quint/src/types/constraintGenerator.ts#L156-L171

I have a fix for this in mind and would like to pick up the issue as a way to ease into work on the type system for #539, assuming no objection from @bugarela.

**Comment by bugarela** [comment]
No objection at all! We actually have an issue for that already: https://github.com/informalsystems/quint/issues/169, I think this one is a sub-issue for that. Perhaps your solution can also address other operators with multiple arity :smile:

**Comment by shonfeder** [comment]
This is a duplicate of #169.
