### ISSUE TITLE
Make `quint verify` user friendly

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#1121]
I really like the fact that `quint verify` is working on my example right now, barring #693. However, the current output is not very user-friendly:

```
$ quint verify --max-steps=10 --invariant=noBeepingWhenHeating kettleTest.qnt
Couldn't connect to Apalache, downloading latest supported release
Using existing Apalache distribution in /Users/igor/.quint/apalache-dist-v0.42.0
Launching Apalache server
Shutting down Apalache server
```

These messages are in principle interesting on a first run, but they are always the same. Moreover, whatever spec is getting is checked successfully, the messages stay the same. It would be much better to have the following:

 1. Introduce the option `quint verify --verbosity` similar to `quint run` and print the above messages only on verbosity greater than 4. We have to figure out the levels. I am just following the Java log levels, where 4 would correspond to DEBUG.

1. On success, produce messages similar to `quint run`, which an experienced user may mute via `--verbosity=0`:

```
[ok] No violation found (491ms).
You may increase --max-steps to obtain better guarantees.
Use --verbosity to produce more (or less) output.
```

**Comment by thpani** [comment]
For (1.), I'm not sure.

The line

```
Couldn't connect to Apalache, downloading latest supported release
```

is important for those who actually want to run Apalache on their own.

Also, in the case that Apalache is not found locally, the second line becomes

```
Downloading Apalache distribution from https://github.com/informalsystems/apalache/releases/download/v0.42.0/apalache.tgz...
```

which is important user feedback, since it may block for some time.

Maybe we should just print those in `chalk.gray()`? @konnov WDYT?

**Comment by konnov** [comment]
Yeah, displaying these messages in gray also sounds good
