### ISSUE TITLE
`verify` is fragile due to dependency on github API

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1124]
Noted on https://github.com/informalsystems/quint/pull/1123#issuecomment-1693512026.

We are hitting github rate limits causing causing invocation of `verify` to fail.

**Comment by shonfeder** [comment]
On github rate limits:

If the github api calls are not made thru an authenticated user account, then the (current) limit is 60 calls per hour. This means, in the current approach where we query the api on every invocation (unless the server is already running), we have a hard choice:

- Users must either start the server manually, or limit themselves to 60

**Comment by shonfeder** [comment]
We should be much more conservative with our API calls, but we're still liable to hit API rate limits in CI: all it takes is running more that 60

**Comment by konnov** [comment]
60 invocations of `verify` per hour is not a big limitation for a single user, as `quint verify` takes at least a few seconds to startup. I guess, this may become a problem, when people sit behind the same IP, like if they are at the same lecture maybe %)

We could reasonably limit version checking to once per hour or once per day. Would that help with CI though?

**Comment by shonfeder** [comment]
I disagree that it's not a big limitation. But in any case, why would we chain the amount of times our CLI tool can be run -- when it has every it needs locally -- to be limited by github's api rate limiting? That doesn't make any sense to me.

**Comment by konnov** [comment]
> I disagree that it's not a big limitation.

I would be curious to learn the reason for disagreeing here. If someone runs `quint verify` in a loop, they should definitely start the server. This feature is mainly designed for first-time users. If somebody runs into that limitation, we should be more clear about how to run the server locally.

**Comment by shonfeder** [comment]
> I would be curious to learn the reason for disagreeing here

A CLI tool that has no intrinsic need to interact over the wire that can only be run 60

**Comment by konnov** [comment]
> > I would be curious to learn the reason for disagreeing here
> 
> A CLI tool that has no intrinsic need to interact over the wire that can only be run 60 times per hour due to accidental complexity is a total turn off to me. If I encountered that kind of arbitrary limit in a tool, I'd want to not use it.

While I agree that good tools should not impose unnecessary complexity, we are still in the MVP stage here, more or less. So if we find a good workaround (e.g., checking for updates once a day), that's great.

**Comment by bugarela** [comment]
I think that the CI failures alone are enough reason to prioritizing a fix here. Intermittent problems in the CI are super annoying.

**Comment by shonfeder** [comment]
So after some digging and thinking:

- We can fix the CI issue by authenticating as noted above
- But, afaik, so long as we depend on hitting the github api to download the artifact, there is no way to fix the problem that if `n` people in a classroom are trying to run `quint verify` for the first time on a shared connection, then `n - 60` people will not be able to run the command because they won't be able to get apalache.

The workaround I've pushed for now is just to use a hard-coded Apalache version and the known download url. This frees us from the github url.

Future work in #1106 can think about the tradeoffs between simplicity and related robustness vs. the desire to accommodate flexibility. 

IMO, we would be better served by not trying to get overly fancy with version management for the moment :)
