### ISSUE TITLE
trace output by `test` disregards the last action

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/quint#1133]
I have a suspicion that `quint test` does not execute the last action. Here is an example:

```
module lastActionInRun {
    var s: str

    action A = 
        s' = "A"
    
    action B = 
        s' = "B"

    
    run t1 = A.then(A).then(B)

    run t2 = A.then(A).then(B).then(s'=s)

    }
```

Upon running `quint test --match=t1 --output=out{#}{}.itf.json lastActionInRun.qnt`, I get two states, `A-A`.

Upon running `quint test --match=t2 --output=out{#}{}.itf.json lastActionInRun.qnt`, I get three states, `A-A-B`

**Comment by konnov** [comment]
Just to double check, is about `quint run`,`quint test`, or both?

**Comment by ivan-gavran** [comment]
It is only about `quint test`, sorry for the typo in the description (edited now)

**Comment by konnov** [comment]
Trying to reproduce this: If you add `fail()` in the end of `t1` or `t2`, you will see an error message. So the simulator is visiting the whole run. Indeed, the output trace does not seem to be complete. This is probably due to using `s' = s` instead of calling an action.

**Comment by konnov** [comment]
@ivan-gavran, does this issue in any way block your work? An answer to this question would help us to prioritize it.

**Comment by ivan-gavran** [comment]
> @ivan-gavran, does this issue in any way block your work? An answer to this question would help us to prioritize it.

It does not. Now that I know of it, I simply add a dummy state to the end.

**Comment by konnov** [comment]
I have been staring at the code for 30 min. No idea why it works this way

**Comment by konnov** [comment]
It looks like it's a bit of postponed work #854

**Comment by konnov** [comment]
ok, I have figured out what's going on. Since `s' = s` is not a user-defined operator, it does not create a new frame. This is definitely the piece of work postponed in #854. Let's see how fast I can implement that.

**Comment by konnov** [comment]
I have made it half-way to fixing this issue in #1158. This still needs another quite a bit of work.
