### ISSUE TITLE
The option --output in quint test requires '.itf.json' extension

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/quint#1137]
If running `quint test` with option `--output` being e.g., `out{#}{}.json`, it complains about getting _Unexpected format in --output_.  (Passing `out{#}{}.itf.json` is fine.)

Why is quint insisting on the extension? Especially given that a similar option `--out-itf` in `quint run` accepts `*.json` files.

**Comment by konnov** [comment]
How does this affect your workflow. This does not seem to be a hinderance of any kind to me.

**Comment by ivan-gavran** [comment]
I noticed it when trying to format the resulting .itf.json in VSCode (which does format .json, but does not .itf.json). There should probably be a VSCode-based fix for my issue, true. 

Regardless of that, I am raising this issue to see whether Quint wants to enforce the extension or if it wants to allow files with any extensions to be generated.
