### ISSUE TITLE
Remove string type

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#118]
TNT doesn't offer support for any string operations, therefore, the string type is just a type with unbounded uninterpreted values. We can remove it and instead support some sort of atom type or just stick to discriminated unions. The main motivation is that using strings for uninterpreted values is prone to typos, where using a more restrictive pre-defined type is safer.

```scala
// strings
var status: str
def A = status = "processing" // => ok
def B = status = "processingg" // => ok

// atoms
var status: :idle | :processing | :off
def A = status = :processing // => ok
def B = status = :processingg // => Error: invalid value for status: :processingg

// discriminated unions
var status = Idle | Processing | Off
def A = status = Processing // => ok
def B = status = Processingg // => Error: Unknown variant constructor: Processingg
```

**Comment by rnbguy** [comment]
Sometimes, I do need to generate random strings. E.g. when testing a blog database with random inputs.

Of course, I can use some hacks e.g. representing the bytes with integers. But getting native string output in Quint traces would be nice.

I think representing `Str` as same as `Seq(Int)` (`Int` is byte) is perfectly reasonable to me.

**Comment by konnov** [comment]
Yeah, I also feel that we need strings for some input/output things, but not as atoms.

**Comment by shonfeder** [comment]
I don't think we'll be removing strings :)
