### ISSUE TITLE
Add support for `apalache simulate`

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#1185]
Currently, `quint verify` calls `apalache-mc check`. It would be great, if we could also call `apalache-mc simulate`, so we could utilize Apalache even for relative complex specs.

Since `quint run` does random simulation, it would be confusing to call this mode "simulation". Perhaps, we could call it something like `quint verify --randomized`. The essential difference is that this mode would choose transitions at random, but evaluate them symbolically, whereas `quint run` chooses transitions at random and evaluates them concretely.

@thpani wdyt?

**Comment by thpani** [comment]
Yeah, I think logically this is much closer to `verify`. Also has the same other parameters.
