### ISSUE TITLE
Lack of shadowing is confusing

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1187]
Take this spec:

```
module Core {
    pure val foo =
        val boo = 3
        boo    
}
```

Loading it into repl, I cannot access `boo` (this is what I would expect)
but I also cannot assign a new variable called `boo` (this is not expected)

```
quint -r test.qnt::Core       
Quint REPL 0.14.3
Type ".exit" to exit, or ".help" for more information
>>> boo
syntax error: error: [QNT404] Name 'boo' not found
boo
^^^


>>> val boo = 3
syntax error: error: [QNT101] Conflicting definitions found for name 'boo' in module 'Core'
val boo = 3
^^^^^^^^^^^

syntax error: error: [QNT101] Conflicting definitions found for name 'boo' in module 'Core'
        val boo = 3
```

This seems related to https://github.com/informalsystems/quint/issues/802, but seems to be a different issue, since it has nothing to do with instancing modules.

Version Info: This is happening after `make`ing quint from the v0.14.3 release branch

**Comment by bugarela** [comment]
This is actually intended (see "No collisions" in our [language manual](https://github.com/informalsystems/quint/blob/main/doc/lang.md#namespaces)).

I'm inclined to change this and allow shadowing, while @konnov thinks it's a good idea to keep it. None of us are sure about our opinions :laughing:.

Changing this would be trivial, it is only a matter of a design decision right now.

**Comment by shonfeder** [comment]
This isn’t really shadowing tho, iiuc. Boo is defined in a nested scope, and should not be in scope when the module is loaded. Afaiu, first invocation of the repl shows that boo is not in scope or defined. But the second shows we still can’t define boo in a context where it isn’t defined.

**Comment by p-offtermatt** [comment]
Hm, looking at the example I could see why this is shadowing.

If it's not a bug, I'm quite convinced this should not be the way it behaves - 'boo' is neither defined nor definable, and just pollutes the namespace. I have a module with quite a few nested definitions like this, and it seems weird that common names that I happen to use in nested scopes are now blocked from being assigned, e.g. because in some nested scope 'result' is defined, I can't use it in the repl anymore.

Another aspect that I think speaks for allowing shadowing is that the best way to debug things in the REPL is sometimes to copy code fragments from the code to see intermediate outputs.
E.g. if this test fails:

```
run VotingPowerSetsFlagTest =
    {
        // change voting power
        val tmpResult = votingPowerChange(
            GetEmptyProtocolState,
            "validator",
            5
        )
        // but then set it back to the initial value
        val finalResult = votingPowerChange(
            tmpResult.newState,
            "validator",
            0
        )
        // still should set the flag
        not(finalResult.hasError) and
        finalResult.newState.providerState.providerValidatorSetChangedInThisBlock
    }
```

what I would do is copy-paste 
```
val tmpResult = votingPowerChange(
            GetEmptyProtocolState,
            "validator",
            5
        )
        // but then set it back to the initial value
        val finalResult = votingPowerChange(
            tmpResult.newState,
            "validator",
            0
        )
``` into the repl and see the both outputs. But this is annoying now, because I have to redefine the name of tmpResult since it's used in a nested scope, and then I have to change the name of tmpResult also in the second call to votingPowerChange, and this quickly cascades for longer tests.

**Comment by bugarela** [comment]
> This isn’t really shadowing tho, iiuc. Boo is defined in a nested scope, and should not be in scope when the module is loaded. Afaiu, first invocation of the repl shows that boo is not in scope or defined. But the second shows we still can’t define boo in a context where it isn’t defined.

Perhaps the matter of order is confusing here. Can you agree that the following is shadowing?
```bluspec
val foo = 1
val bar = val foo = 2 { foo }
```

I think this is clear shadowing, and Philip's case is just reversing the order of definitions. First, something like `bar` is defined, and then we try to define `foo`, which would create shadowing for the existing `foo` inside `bar`'s context.

**Comment by shonfeder** [comment]
Oh yeah. The example you show is clearly shadowing. I see know what you are saying: the fact that we support unordered definitions means that by adding a top level definition later in a file you can can end up making a nested let binding earlier in the file becoming “shadowing”. And this is applying even in the repl, which behaves as tho it is an imperative update of declarations.

this is extremely confusing XD  . Imo we must clearly either ditch out of order definitions or allow shadowing.

**Comment by bugarela** [comment]
@corazza reported also having issues with LLM-related work because of lack of shadowing, since most languages allow shadowing. Since most of our users complained about this already, and we don't have strong reasons to actually forbid shadowing completely, we decided to allow it. 

In the future, when we have a proper warning system in place, we can emit warnings on shadowing (which should be potentially disabled via configuration).

I'll re-use this issue to track work on enabling shadowing.
