### ISSUE TITLE
Importing by path breaks on case-insensitive file systems

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1194]
Take this folder of specs:
https://github.com/cosmos/interchain-security/blob/aa2989e40e6fb4578adb5e6b94752c36670f3cdc/tests/difference/core/quint_model

Importantly, note this import statement:

https://github.com/cosmos/interchain-security/blob/aa2989e40e6fb4578adb5e6b94752c36670f3cdc/tests/difference/core/quint_model/ccv_statemachine.qnt#L4

If I change the line to
```
import Time.* from "./libraries/time"
```

both the vscode plugin and the quint typechecker give me errors (here is the error from the plugin):
```
[QNT102] Module with name 'Time' was already definedquint(QNT000)
```

Any capitalization other than `Time`, i.e. `timE`, `TIME`, ... does not work.
This seems like a bug - the capitalization in the filename does not seem to matter usually, i.e.
this works fine:

```
module Test {
    import Test2 from "./foo/test2"
}
```
and in file `foo/test2.qnt`
```
module Test2 {
}
```
works ok.
Also, now any capitalization works -
```
 import Test2 from "./fOo/TeSt2"
```
works fine. Not sure what is special about my spec to break it.

**Comment by bugarela** [comment]
@konnov @thpani can one of you see if you can reproduce this? Linux filesystem in case sensitive, and I'm not being able to reproduce the same error here. If I try any casing different than the file's casing, I get a proper error:
```
error: import ... from './libraries/Time': could not load
221:     import Time.* from "./libraries/Time"
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: parsing failed
```

**Comment by p-offtermatt** [comment]
Just to add the context we discussed on Slack, I am on MacOS, which is case insensitive, so that all capitalizations are working for me is likely the expected behaviour

**Comment by bugarela** [comment]
Yep! We should either allow that capitalization or report a proper error.

**Comment by thpani** [comment]
Can confirm on macOS/APFS. Changing all imports (also those in `ccv.qnt`) resolves the issue.

**Comment by bugarela** [comment]
Ah, yes! That might be it. Thanks for the pointer, I was clueless.

**Comment by konnov** [comment]
> Can confirm on macOS/APFS. Changing all imports (also those in `ccv.qnt`) resolves the issue.
> 
> @bugarela I'd guess we're tracking imported modules somewhere by filename, and so two case-sensitive paths to the same (case-insensitive) file/module end up clashing?

@thpani, you are right. This is exactly what is happening in file imports:

https://github.com/informalsystems/quint/blob/bf85b5fb1a8c9b1057ec104a6251056fa2b2461e/quint/src/parsing/quintParserFrontend.ts#L182-L185

**Comment by konnov** [comment]
I wanted to fix that. However it is not clear to me, what approach we should take. The simplest one would be to simply compare lower-cased versions of filenames. However, [NodeJS guidelines](https://nodejs.org/en/guides/working-with-different-filesystems) advise against this approach. Now it is a bit tricky, since filenames are not only platform-dependent but also filesystem-dependent. Some people recommend creating a temporary file and testing whether it is accessible via its upper-case version. However, this would require write permissions in the same directory where the file is located. Also, testing a temporary file in `TEMPDIR` may be misleading, as `TEMPDIR` may be mounted to a different filesystem.

**Comment by konnov** [comment]
I guess, I could also check whether the same file is accessible via both uppercase and lowercase. That would not require write permissions at least

**Comment by p-offtermatt** [comment]
@konnov No worries - I am happy with this, as long as it's easy to understand what you need to do to fix it when it breaks!
