### ISSUE TITLE
Crashing when no main module is given

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1195]
I am getting the same error as https://github.com/informalsystems/quint/issues/1192, but I think for a different reason, namely for an omitted main module.
The spec is here: https://github.com/cosmos/interchain-security/blob/c291303159ce3c28cf00484e34252e07fd94bffc/tests/difference/core/quint_model/ccv_statemachine.qnt#L164

and I am running 

```
quint run --invariant ValidatorUpdatesArePropagated ccv_statemachine.qnt
```

This crashes:

```
TypeError: Cannot read properties of undefined (reading 'id')
    at runSimulator (/Users/offtermatt/projects/quint/quint/dist/src/cliCommands.js:376:63)
    at EitherConstructor.asyncChain (/Users/offtermatt/projects/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:125:16)
    at /Users/offtermatt/projects/quint/quint/dist/src/cli.js:33:39
```

When I run it with a main module, it does not crash:

```
quint run --invariant ValidatorUpdatesArePropagated ccv_statemachine.qnt --main CCVDefaultStateMachine
```

I think there should be a dedicated error message for this case

**Comment by konnov** [comment]
Yeah, this clearly looks like a CLI bug to me
