### ISSUE TITLE
Missing module name in error message

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1198]
This is my spec: https://github.com/cosmos/interchain-security/blob/e494a094ce629537303e6673bcd374fcc31fafc0/tests/difference/core/quint_model/ccv_statemachine.qnt#L118

This is the command I am running:
```
quint run --invariant ValidatorSetHasExistedInv ccv_statemachine.qnt --main CCVDefaultStateMachine --max-steps 500 --max-samples 200
```

This is the part of the output that is unexpected:

```
[violation] Found an issue (881ms).
Use --seed=0x1ee0a2933259d1 to reproduce.
Use --verbosity=3 to show executions.
<module_input>:118:24 - error: Applied oneOf to an empty set
118:         nondet chain = oneOf(runningConsumers)
```

Notice the error location: It just says `module_input` instead of the actual module.
This should probably give the filename.
This works best with nice features that my ide would give me if instead of module_input,
i.e. if this said `ccv_statemachine.qnt:118:24`, then clicking it would bring me right to the line in question in VSCode.

**Comment by bugarela** [comment]
This was fixed by https://github.com/informalsystems/quint/pull/1211
