### ISSUE TITLE
Implement ToApalache task

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#12]
As outlined in [ADR001](https://github.com/informalsystems/tnt/blob/main/doc/adr001-transpiler-architecture.md#36-toapalache), we should implement TNT to Apalache IR translation task.

Factoring out some sub-tasks:

- [x] Deserialization of TNT expressions and types into Scala
- [x] informalsystems/quint#349
- [x] informalsystems/apalache#2350
- [x] tnt expressions -> Apalache expressions: https://github.com/informalsystems/apalache/milestone/74

**Comment by shonfeder** [comment]
gg
