### ISSUE TITLE
`verify --apalache-config` does not accept HOCON

### ISSUE THREAD

**Issue by thpani** [informalsystems/quint#1215]
`quint verify --apalache-config` claims to accept a HOCON file:

```sh
$ quint verify
quint verify <input>
[...]
  --apalache-config     Filename of the additional Apalache configuration (in
                        the HOCON format, a superset of JSON)           [string]
```

However, we internally rely on `JSON.parse` to read the file:

https://github.com/informalsystems/quint/blob/e693293008e07871d8976aaabb7d5c55dc0ab06d/quint/src/cliCommands.ts#L574

which leads to the following stack trace, if passing a HOCON file:

```
SyntaxError: Unexpected token 'c', "checker {
"... is not valid JSON
    at JSON.parse (<anonymous>)
    at verifySpec (/Users/thomas/src/quint/quint/dist/src/cliCommands.js:442:53)
    at EitherConstructor.asyncChain (/Users/thomas/src/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:125:16)
```

We should either improve parsing support, or update the docs to only mention JSON as a supported format.

**Comment by konnov** [comment]
I am fine with supporting JSON only

**Comment by shonfeder** [comment]
Same. This was a documentation bug introduced by me during review I think.
