### ISSUE TITLE
Minor improvement request: Automatically detecting the main module even when it's not the same as the file name

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1219]
I have a file that contains a single module, e.g. a file called spec.qnt:
```
module Alpha {
...
}
```

When I try to run tests, e.g. 
```
quint test spec.qnt 
```
then Quint complains that it cannot find the main module, because it assumes the main module
has the same name as the file:
```
  spec
error: Cannot find main module
error: Tests failed
```

I'd argue that if there is a file with only a single module in it and I run quint against it, it should just take that one module as the main module. Of course, maybe the current way helps encourage the desired practice of naming the main module the same as the file, but I'm not sure there's a reason for this.

Maybe I am overlooking something here, but my preferred behaviour would be: if the file contains a single module, just use that as the main module. If it contains multiple modules, use the module with the same name as the file name if one exists. If not, complain.

**Comment by konnov** [comment]
Yeah, we can do it this way too.
