### ISSUE TITLE
Error when running 'quint verify'

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1235]
Hey, I am running into a problem when trying to use Apalache on my spec.

Quint version:
```
% quint --version
0.14.4
```

Spec: https://github.com/cosmos/interchain-security/blob/ph/mbt/tests/difference/core/quint_model/ccv_model.qnt#L319

Error log:
```
% quint verify ccv_model.qnt --invariant CanStopConsumer --verbosity 5
No running Apalache server found, launching...
Using existing Apalache distribution in /Users/offtermatt/.quint/apalache-dist-0.42.0/apalache/bin/apalache-mc
Launching Apalache server
error: internal error: while parsing in Apalache:
'Input was not a valid representation of the QuintIR: Conversion failed while building operator definition `ccv_model::ccv::endAndBeginBlockForConsumer`: Operator EXCEPT cannot be applied to arguments of types ({ chainState: { currentValidatorSet: (Str -> Int), lastTimestamp: Int, votingPowerHistory: Seq((Str -> Int)) }, maturationTimes: (f -> g), outstandingPacketsToProvider: Seq({ id: h, sendingTime: Int }), receivedVscPackets: Seq({ id: Int, sendingTime: Int, validatorSet: (Str -> Int) }) }, <<Str>>, (p -> q))'
Please report an issue: https://github.com/informalsystems/quint/issues/new
Shutting down Apalache server
```

However, quint run works fine:
```
% quint run --invariant CanStopConsumer ccv_model.qnt
[...]
[violation] Found an issue (901ms).
Use --seed=0xa95475f0232ff to reproduce.
Use --verbosity=3 to show executions.
error: Invariant violated
```

Extra info that might be useful:
```
% java --version
openjdk 21.0.1 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)
```

**Comment by shonfeder** [comment]
Thanks for the report.

Unrelated, but looking at the spec, I suspect using our record update syntax sugar would improve readability over chained applications of `with`. E.g.,

```
>>> val r = {a: 0, b: 1, c: 2}

>>> r.with("a", 2).with("b", 1).with("c", 0)
{ a: 2, b: 1, c: 0 }
>>> {...r, a: 2, b: 1, c: 0}
{ a: 2, b: 1, c: 0 }
```

**Comment by shonfeder** [comment]
For debugging, here's the error message reformatted to make it clear what we are failing to typecheck in `EXCEPT`:

```
'Input was not a valid representation of the QuintIR: Conversion failed while
building operator definition `ccv_model::ccv::endAndBeginBlockForConsumer`:
Operator EXCEPT cannot be applied to arguments of types 

({ chainState: { currentValidatorSet: (Str -> Int), lastTimestamp: Int, votingPowerHistory: Seq((Str -> Int)) }, 
   maturationTimes: (f -> g),
   outstandingPacketsToProvider: Seq({ id: h, sendingTime: Int }),
   receivedVscPackets: Seq({ id: Int, sendingTime: Int, validatorSet: (Str -> Int)})},
<<Str>>,
(p -> q))'
```

**Comment by shonfeder** [comment]
I suspect the error is happening on an update to `maturationTimes` (given the signature of the updated value).

The types for those maps (`f -> g` and `p -> q`) is suspicious to me, as I thought we are expecting Quint to have inferred monomorphic types for these before sending it to Apalache.

If my suspicion is right, that we may be choking here:

https://github.com/cosmos/interchain-security/blob/a4840fcbd5a1bd3aaad1a9b9daf29115f806bb8b/tests/difference/core/quint_model/ccv.qnt#L476-L477

Updating https://github.com/cosmos/interchain-security/blob/a4840fcbd5a1bd3aaad1a9b9daf29115f806bb8b/tests/difference/core/quint_model/ccv.qnt#L476 with an annotation

```
                val newConsumerState2: ConsumerState = newConsumerState.with(
```

We can get a different break:

```
error: internal error: while parsing in Apalache:
'Input was not a valid representation of the QuintIR: No entry found for id 3368 in lookup table'
Please report an issue: https://github.com/informalsystems/quint/issues/new
```

**Comment by shonfeder** [comment]
More debugging notes:

Dumping the symbol table and type maps:

```
$  quint typecheck --out t.json ccv.qnt 
```

We can then get a list of all the paths that go to the `newConsumerState2` value:

```
$  jq -c 'paths as $p | select(getpath($p) == "newConsumerState2") | $p' < t.json
["modules",3,"declarations",33,"expr","expr","args",2,"expr","expr","expr","expr","expr","expr","opdef","name"]
["modules",3,"declarations",33,"expr","expr","args",2,"expr","expr","expr","expr","expr","expr","expr","opdef","expr","args",2,"name"]
["table","761","name"]
["table","766","expr","args",2,"name"]
```

Then inspect the way we are representing it in the symbol table

```
$  jq '.table["761"]' < t.json
{
  "id": 756,
  "kind": "def",
  "name": "newConsumerState2",
  "qualifier": "val",
  "expr": {
    "id": 755,
    "kind": "app",
    "opcode": "with",
    "args": [
      {
        "id": 752,
        "kind": "app",
        "opcode": "with",
        "args": [
          {
            "id": 749,
            "kind": "name",
            "name": "newConsumerState"
          },
          {
            "id": 750,
            "kind": "str",
            "value": "maturationTimes"
          },
          {
            "id": 751,
            "kind": "name",
            "name": "newMaturationTimes"
          }
        ]
      },
      {
        "id": 753,
        "kind": "str",
        "value": "outstandingPacketsToProvider"
      },
      {
        "id": 754,
        "kind": "name",
        "name": "newOutstandingPackets"
      }
    ]
  },
  "depth": 1
}
```

And finally how it is being typed:

```
$  jq '.types["756"]' < t.json
{
  "typeVariables": {},
  "rowVariables": {},
  "type": {
    "kind": "rec",
    "fields": {
      "kind": "row",
      "fields": [
        {
          "fieldName": "outstandingPacketsToProvider",
          "fieldType": {
            "kind": "list",
            "elem": {
              "kind": "rec",
              "fields": {
                "kind": "row",
                "fields": [
                  {
                    "fieldName": "id",
                    "fieldType": {
                      "kind": "var",
                      "name": "_t1040"
                    }
                  },
                  {
                    "fieldName": "sendingTime",
                    "fieldType": {
                      "id": 3,
                      "kind": "int"
                    }
                  }
                ],
                "other": {
                  "kind": "empty"
                }
              }
            },
            "id": 6
          }
        },
        {
          "fieldName": "maturationTimes",
          "fieldType": {
            "kind": "fun",
            "arg": {
              "kind": "var",
              "name": "_t1037"
            },
            "res": {
              "kind": "var",
              "name": "_t1038"
            },
            "id": 8
          }
        },
        {
          "fieldName": "chainState",
          "fieldType": {
            "kind": "rec",
            "fields": {
              "kind": "row",
              "fields": [
                {
                  "fieldName": "lastTimestamp",
                  "fieldType": {
                    "id": 3,
                    "kind": "int"
                  }
                },
                {
                  "fieldName": "votingPowerHistory",
                  "fieldType": {
                    "id": 28,
                    "kind": "const",
                    "name": "VotingPowerHistory"
                  }
                },
                {
                  "fieldName": "currentValidatorSet",
                  "fieldType": {
                    "id": 29,
                    "kind": "const",
                    "name": "ValidatorSet"
                  }
                }
              ],
              "other": {
                "kind": "empty"
              }
            }
          }
        },
        {
          "fieldName": "receivedVscPackets",
          "fieldType": {
            "id": 82,
            "kind": "list",
            "elem": {
              "id": 81,
              "kind": "const",
              "name": "VscPacket"
            }
          }
        }
      ],
      "other": {
        "kind": "empty"
      }
    }
  }
}
```

**Comment by shonfeder** [comment]
we can see that `maturationTimes` is indeed being typed as a map `a -> b`:

```
          "fieldName": "maturationTimes",
          "fieldType": {
            "kind": "fun",
            "arg": {
              "kind": "var",
              "name": "_t1037"
            },
            "res": {
              "kind": "var",
              "name": "_t1038"
            },
            "id": 8
          }
```

I believe this is incorrect, since in the context of the spec we have all info we need to be able to fully infer the type of the map, based on the earlier declaration in

https://github.com/cosmos/interchain-security/blob/a4840fcbd5a1bd3aaad1a9b9daf29115f806bb8b/tests/difference/core/quint_model/ccv.qnt#L102-L119

**Comment by bugarela** [comment]
Hey! Thanks both of you for all the context. I think this might be a type alias issue, and might be related to what I believe is the root cause of https://github.com/informalsystems/quint/issues/1177. I'll try to change when/how aliases are unified and check if the behavior changes.

**Comment by bugarela** [comment]
There are definitely two problems here, one in type inference and other in (probably) flatenning.

For the problem with types, annotating the type as @shonfeder suggested [here](https://github.com/informalsystems/quint/issues/1235#issuecomment-1792529799) works. I also have something WIP that solves the problem without requiring the annotation.

Solving the type problem unlocks this "No entry found for id 3367 in lookup table" issue, which I'll investigate now.

**Comment by bugarela** [comment]
Ok, found problem 2. You can't use `oneOf` like this:
https://github.com/cosmos/interchain-security/blob/a4840fcbd5a1bd3aaad1a9b9daf29115f806bb8b/tests/difference/core/quint_model/libraries/extraSpells.qnt#L195
```bluespec
pure def maxBy(__set: Set[a], __f: a => int): a = {
  __set.fold(
    oneOf(__set),
    (__m, __e) => if(__f(__m) > __f(__e)) {__m } else {__e}
  )
}
```

Quint simulator can handle it, but this is not valid for apalache. The effect checker still doesn't know a lot about `nondet` and `oneOf`, so it won't complain, but it should (https://github.com/informalsystems/quint/issues/381). So you don't see a proper error - as I have noticed previously but completely forgot about https://github.com/informalsystems/quint/issues/381#issuecomment-1727933080

Unfortunately, as we discussed at the retreat, there's currently no way of picking an element out of a set. I tried a bunch of alternatives but they all suck. I managed to make it work and get apalache to run locally after adding the annotation and getting rid of the `oneOf` in `maxBy` and `minBy`. I think the best way for now is to make `minBy` and `maxBy` less generic (take a packet instead of an arbitrary type `a`) and have a initial min and max as some packet with `sendingTime` set to 0/9999999999.

PS: I hit some pretty strange effect issues when trying to rewrite `minBy`/`maxBy`, so don't waste too much time trying to figure things out if you hit them - just let me know and we can try some workarounds.

**Comment by p-offtermatt** [comment]
Alright, thanks, I will try that out! Thank you for looking into this!

**Comment by p-offtermatt** [comment]
I fixed the minBy/maxBy errors by making dedicated functions just for packets.

For the annotations, I ran into several more issues of the same nature, but I managed to work around them by liberally sprinkling type annotations, so now I was able to run my verification and got the expected result, thank you!

**Comment by shonfeder** [comment]
ff
