### ISSUE TITLE
Fix the grammar: an operator definition should use `qualId`

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#1247]
Instead of `normalCallName`, the syntax rule for the operator definition should refer to `qualId`. It should not be possible to use the builtin operators in new definitions.

https://github.com/informalsystems/quint/blob/15596529a44749255219d211ef5e4960d09b198a/quint/src/generated/Quint.g4#L44

**Comment by konnov** [comment]
Blocked by  the discussion in #1249

**Comment by shonfeder** [comment]
It sounds like this is not actually causing problems currently, and we have better error reporting UX with the current approach, so we'll close this for the moment. If end up with a clear problem posed by this quirk in our grammar we can rethink.
