### ISSUE TITLE
Automate local updates of VSCode plugin

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#125]
Suggested by Shon https://github.com/informalsystems/tnt/pull/120#discussion_r920122365

Whenever we update either `tntc`, the plugin server or the plugin client, there is a different set of commands that need to be run to apply the changes. They are currently described in the README.md, but we should have npm scripts for them to improve quality of life.

**Comment by shonfeder** [comment]
Is this taken care of by `make local` @bugarela ?

**Comment by bugarela** [comment]
yep, this has been working smoothly for me lately :D
