### ISSUE TITLE
write post-condition assertions without introducing a new step

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#1252]
@hvanz reported an issue where he is trying to have an assertion after an action, and that produces a stuttering step which is not wanted.

He thought the built in `assert` could be interpreted in such a way where the step with the assertion doesn't make it through the trace. This is not true, but it is a valid idea.

Also https://github.com/informalsystems/quint/issues/1236 might help solving this issue.

**Comment by hvanz** [comment]
> introduce post-conditions inside runs.
Yes, probably that what's needed here.

So, given that a typical way of writing tests is:
```
run fooTest = 
  init
    .then(action1)
    .then(all { assert(property1), unchangedAll })
    .then(action2)
    .then(all { assert(property2), unchangedAll })
```
then the generated trace from this run will contain the two undesired steps from `unchangeAll`. I couldn't find a good way to rewrite this test to avoid generating stuttering steps.

I thought ideally one could write something like the following, with `.assert(...)` (or other name) as post-condition:
```
run fooTest = 
  init
    .then(action1)
    .assert(property1)
    .then(action2)
    .assert(property2)
```
Then internally it would be easier to distinguish which states must be discarded when generating the trace.

**Comment by shonfeder** [comment]
The proposed post-condition assert makes since to me. 

But isn't `unchangedAll` only needed in the last step of a run, in cases where you want to assert something in a final state? E.g., couldn't the first example be

```
run fooTest = 
  init
    .then(action1)
    .then(all { assert(property1), action2 })
    .then(all { assert(property2), unchangedAll })
```

**Comment by hvanz** [comment]
This is equivalent but the problem is still there in the last state, right? Also I think it could be confusing to have `property1` and `action2` in the same line, with `property1` referring to the action in the line above.

**Comment by konnov** [comment]
Just thinking about it. Probably the easiest solution would be to introduce an operator that works similar to  `then` in the sense then it shifts primed variables to non-primed, but it evaluates the predicate and discards the new state.
