### ISSUE TITLE
Add syntax to allow arbitarary operators to be applied infix

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#126]
Haskell provides [a method of applying prefix functions as infix](https://wiki.haskell.org/Infix_operator#Using_prefix_functions_with_infix_notation). Given a function `f : a -> b -> c` you can apply as infix by enclosing it in backticks, like 

```haskell
x `f` y
```

Providing some sugar like this would allow us the benefits of flexible infix operator application without the ambiguity resulting from the pervasive infix operator application removed in #122

**Comment by konnov** [comment]
I think we have decided not to go this way some time ago, `x.f(y)` is a good enough substitution for infix operators. Closing this issue.
