### ISSUE TITLE
Bug in the type inference system involving nested sum types and tuples

### ISSUE THREAD

**Issue by hvanz** [informalsystems/quint#1302]
In the following example, the definition `wrap2` has an incorrect inferred type `∀ t0 . t0`, which is then possible to misuse in any desired way.
```
module example {
    type T = None | Some(int)
    pure def f(t) = match t { None => Some(1) | Some(n) => Some(n+1) }

    type W = Wrap(T)

    type P = Pair((W, W))
    pure def g(__pair: P): W = match __pair {
    | Pair(__p) => 
        val wrap1 = __p._1 // inferred type: "val wrap1: W"
        val wrap2 = __p._2 // inferred type: "val wrap2: ∀ t0 . t0"
        Wrap(wrap2) // <== this should not be possible
    }

    var p: P
    action init = p' = Pair((Wrap(None), Wrap(Some(1))))
    action step = p' = Pair((g(p), g(p)))
    run pTest = init.then(step).then(step).then(step)
}
```
After running `pTest`, the value of `p` is `Pair((Wrap(Wrap(Wrap(Wrap(Some(1))))), Wrap(Wrap(Wrap(Wrap(Some(1)))))))`.

**Comment by hvanz** [comment]
The temporary solution to surface the error in the above example is to annotate `wrap2` with the correct type `W`.

**Comment by shonfeder** [comment]
Thank you very much for adding this reproduction. It will save a tine of time in debugging :)

**Comment by shonfeder** [comment]
@bugarela has just helped by noting that this is an instance of a known problem with type inference in let bindings. To demonstrate, if we remove the let bindings, we get the expected error. I.e., the following with fail the with the expected (inscrutable) error:

```quint
module example {
    type T = None | Some(int)
    pure def f(t) = match t { None => Some(1) | Some(n) => Some(n+1) }

    type W = Wrap(T)

    type P = Pair((W, W))

    pure def g(__pair: P): W = match __pair {
    | Pair(__p) =>
        // val wrap1 = __p._1 // inferred type: "val wrap1: W"
        // inferred type: "val wrap2: ∀ t0 . t0"
        Wrap(__p._2) // <== this should not be possible
    }

    var p: P
    action init = p' = Pair((Wrap(None), Wrap(Some(1))))
    action step = p' = Pair((g(p), g(p)))
    run pTest = init.then(step).then(step).then(step)
}
```

**Comment by bugarela** [comment]
Should be this one: https://github.com/informalsystems/quint/issues/1167

And might be related to this one as well: https://github.com/informalsystems/quint/issues/1013

**Comment by shonfeder** [comment]
Ah indeed: i think it is exactly #1167. Thanks!

**Comment by shonfeder** [comment]
Closing this as a dulpicate.
