### ISSUE TITLE
Add an intro/quick start tutorial that is more focused

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1319]
Our "Hello, World!" tutorial is a tutorial on how to specify a hello world program rather than a "hello world" for writing specs in quin. We can make more gentle intro by having a more focused tutorial that just describes the most basic concepts and usage.

Thanks to feedback from user Nevermark on HN for this feedback: https://news.ycombinator.com/item?id=38712176

**Comment by elimisteve** [comment]
Yes, start super basic then build up from there please; good idea. Then we understand the building blocks before trying to understand a medium complexity example that uses those building blocks. 👌

**Comment by bugarela** [comment]
I wrote a new Getting Started guide here: https://quint-lang.org/docs/getting-started

I think it is quite straight-forward while still showing the whole story. I'll close this but lmk if anyone still thinks we need to improve it (and how).
