### ISSUE TITLE
Incorrect hover annotations

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1326]
Take this spec:
https://github.com/cosmos/interchain-security/blob/214f6e5c25346b9d3287be8337201f2d15ba538a/tests/mbt/model/ccv.qnt#L337

In particular, this function:
```
    pure def AppendConsumerAddrToPrune(currentState: ProtocolState, oldConsAddr: ConsumerAddr): ProtocolState = {
        pure val vscId = currentState.providerState.runningVscId
        pure val consumerAddrsToPrune = currentState.providerState.consumerAddrsToPrune
        pure val prevConsAddr = consumerAddrsToPrune.get(oldConsAddr).getOrElse(vscId, [])

       pure val newConsAddrsToPrune = consumerAddrsToPrune

       currentState
    }
```

when I hover over consumerAddrsToPrune, I get this info:
![image](https://github.com/informalsystems/quint/assets/57488781/ab6095e7-2978-46ab-be90-5ad2072b93b8)
which is not very useful - I want to find the type of consumerAddrsToPrune, which is defined like this:

```
    type ProviderState =
        {
            [...]
            consumerAddrsToPrune: Chain -> VscId -> List[ConsumerAddr],
        }
```

The field curiously also doesn't show up when I hover over `providerState`:

![image](https://github.com/informalsystems/quint/assets/57488781/8d3232ef-7fb4-4b7c-8c8b-eb9e3ad9f549)

It seems this is only broken in this particular function, not everywhere. See how I think it should look, hovering over a providerState somewhere else (red circle for emphasis):
![image](https://github.com/informalsystems/quint/assets/57488781/ca5ad6f4-efbb-436f-ad94-9cf19da93347)

Not sure I'm missing something subtle, or this is a genuine bug.

```
% quint --version
0.18.0
```

**Comment by shonfeder** [comment]
I suspect this may just be a symptom of https://github.com/informalsystems/quint/pull/975#issuecomment-1651191567. WDYT @bugarela ?

**Comment by bugarela** [comment]
That issue is more specific, I believe, to nested tuples. I think this is more related to https://github.com/informalsystems/quint/issues/1013, since currently we don't use the type annotation information "as much" as we should. And there is something going wrong in reconciling inferred types with annotated ones, causing things similar to this hovering issue iirc.

**Comment by bugarela** [comment]
This seems to have been fixed! Likely when we fixed https://github.com/informalsystems/quint/issues/1177
