### ISSUE TITLE
Unhelpful error location for type mismatch

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1328]
In this spec:
https://github.com/cosmos/interchain-security/blob/e52e0ce375166dd34de03114b5c96de4cf214b85/tests/mbt/model/ccv.qnt#L300

I get an error here, on line 327:
![image](https://github.com/informalsystems/quint/assets/57488781/3e0e0e66-029d-40f3-b243-3ed94ad52a92)

In fact, the error is on line 300, because provCurValSet is not a set, but a map:
```
if (provCurValSet.exists(node => node != providerNode and node == consumerAddr)) {
```

should be

```
if (provCurValSet.keys().exists(node => node != providerNode and node == consumerAddr)) {
```

It would be great if the error was indicated on line 300.
From the type annotation of
```
assignConsumerKey
```
it is clear (at least to my human reasoning engine) that provCurValSet is a map.
Would it be possible to indicate the error there? It feels weird that the error is indicated later because now the two uses of it don't match, when the first use clearly violated the type declaration of the parameter.

**Comment by shonfeder** [comment]
Thanks for the report! I'm not able to follow the link for your spec. Could you double check it? Thanks :)

**Comment by p-offtermatt** [comment]
My bad, fixed that!

**Comment by shonfeder** [comment]
I think this is a duplicate of #1177, so will close in favor of that one.

Also, I think this is the same issue that Jan raised last week, interfering with his work a bit.
