### ISSUE TITLE
Select a permanent, non-holiday example for the README

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1329]
The secret Santa example was great for the holidays! For the indefinite future, we should put in place an example that is, ideally:

- Short
- Concerns a concurrent system
- Is easy for non-specialists to understand

Perhaps modeling race conditions when multiple processes want to write to a file? Something familiar from a working programmers daily life would let us tap into intuition.

**Comment by bugarela** [comment]
I selected a bank example for the README/website
