### ISSUE TITLE
Do something about `punycode` deprecation warning

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#1343]
From Node 21, one of our indirect dependencies (`punycode`) is deprecated. We should deal with that.

This is the warning that is shown when someone calls our CLI with node 21:
```
(node:2145150) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by shonfeder** [comment]
These have become errors now, the debt collector came calling :)

**Comment by shonfeder** [comment]
We are pulling in the problematic use of `punycode` thru the `node-fetch` dependency, and hitting https://github.com/node-fetch/node-fetch/issues/1797

This should be fixed in `node-fetch` v3, but there are some breaking API changes we'll have to account for.

**Comment by shonfeder** [comment]
Not only do we have breaking changes in the node-fetch that fixes this depreciation issue, but also typescript compatibility has been lost with the latest version, https://github.com/node-fetch/node-fetch/issues/1617

Dropping this dependency would be the best option, I think.
