### ISSUE TITLE
Add the version number to `quint`

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#135]
Both `quint` and `quint repl` would benefit from the version number

**Comment by thpani** [comment]
I've done a brief exploration after [Lazaro ran into this](https://informalsystems.slack.com/archives/C043C01N3SA/p1679006146858189?thread_ts=1678993558.729469&cid=C043C01N3SA).

`process.env.npm_package_version` is only attached if the app starts through `npm`, not if started directly through nodejs.

Two possible solutions are:
- Replacing it in a `precompile` npm script, as in
  - https://stackoverflow.com/a/48619640/1161037 option (3), or
  - https://stackoverflow.com/a/67701490/1161037
- Using [`genversion`](https://www.npmjs.com/package/genversion)

**Comment by konnov** [comment]
Somehow `quint --version` is showing the version number via yargs. If we could extract this string, we could just pass it to REPL. I will give a try for 15 minutes to do that.

**Comment by konnov** [comment]
The [yargs docs](https://yargs.js.org/docs/#api-reference-version) say the following:

```
Add an option (e.g. --version) that displays the version number (given by the version parameter) and exits the process. By default yargs enables version for the --version option.

If no arguments are passed to version (.version()), yargs will parse the package.json of your module and use its version value.

If the boolean argument false is provided, it will disable --version.
```
