### ISSUE TITLE
Apalache is inferring overly general types for operators with polymorphic types

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1393]
Running

```
quint verify ../examples/language-features/option.qnt
```

gives

```
error: internal error: while type checking in Apalache:
'unknown location,optionMap's type annotation ((None({  }) | Some(b), ((b) => c)) => None({  }) | Some(a)) is too general, inferred: ((None({  }) | Some(b), ((b) => a)) => None({  }) | Some(a))'
```

But the annotations and inferred types produced with

```
x  quint typecheck ../examples/language-features/option.qnt  --out t.json
```

All look to match the correct typing

```
def optionMap(o: Option[a], f: a => e): Option[b]
```

This may need further investigation on the quint side, but I suspect an issue with the apalache conversion.

**Comment by bugarela** [comment]
Might be related, I just hit this problem with a zero-to-hero spec:
```
'Input was not a valid representation of the QuintIR: Conversion failed while building operator definition `bank::send`: Operator application argument types
(((Str -> (Str -> Int))) => Err(k) | Ok({ attributes: Seq(h), data: None({  }) | Some(j), events: Seq(i), messages: Seq(g) })) do not unify with the operator type
(({ attributes: Seq(h), data: None({  }) | Some(j), events: Seq(i), messages: Seq(g) }) => Err(k) | Ok({ attributes: Seq(h), data: None({  }) | Some(j), events: Seq(i), messages: Seq(g) })) in bank::Ok(bank::new_bank_1622()).'
```

**Comment by bugarela** [comment]
After some investigation, I feel like there might be something wrong on how Apalache is getting the types from Quint. Seems like Quint produces the correct types for both cases, but somehow Apalache is reporting a wrong expected type for them.

**Comment by shonfeder** [comment]
Yeah, that is also what I suspected. I think we are introducing extra fresh variables in the Apalache conversion.

**Comment by shonfeder** [comment]
I wonder if the logic could be off in https://github.com/informalsystems/apalache/blob/efffa24640faeb609a9f9d49038c1aa99ad6a37b/tla-io/src/main/scala/at/forsyte/apalache/io/quint/QuintTypeConverter.scala#L18-L36 or if it's something more subtle...
