### ISSUE TITLE
The ITF trace produced by quint verify is not formatted correctly

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/quint#1448]
When running `quint verify ...`, the resulting ITF trace does not adhere to the ITF trace format: instead of being a JSON object (`{...}`), it is an array containing a single JSON object (`[{...}]`). An example is given in [out.itf.json](https://github.com/informalsystems/quint/files/15414165/out.itf.json).

This does not happen when running Apalache directly on a TLA+ file.

**Comment by romac** [comment]
@bugarela Was this fixed in https://github.com/informalsystems/quint/pull/1365?

**Comment by bugarela** [comment]
> @bugarela Was this fixed in #1365?

No, that only touched the simulator (`quint run`) output and I almost made the same mistake as here, but noticed and fixed.

This one should be a simple fix tho, I'll mark it as good-first-issue and perhaps @MahtabNorouzi can work on it next month
