### ISSUE TITLE
grammar: consider adding support for hashbang scripting

### ISSUE THREAD

**Issue by lucab** [informalsystems/quint#1500]
This is a new-feature request for Quint grammar.

I recently added an example which contains this human-readable comment:
https://github.com/informalsystems/quint/blob/75eac364917c9ac7150f61aa15006d62bf3eecba/examples/classic/distributed/TeachingConcurrency/teachingConcurrency.qnt#L6-L7

However, on Unix systems I'd like to be able to directly run this model as `./teachingConcurrency.qnt`, by adding a starting hashbang line like the following:
```
#!/usr/bin/env -S quint verify --temporal correct
```

This is not currently possible because the starting `#` is not a valid token:
```
./teachingConcurrency.qnt:1:1 - error: [QNT000] token recognition error at: '#'
1: #!/usr/bin/env -S quint verify --temporal correct
   ^

./teachingConcurrency.qnt:1:2 - error: [QNT000] token recognition error at: '!/'
1: #!/usr/bin/env -S quint verify --temporal correct
    ^

./teachingConcurrency.qnt:1:4 - error: [QNT000] mismatched input 'usr' expecting {'module', DOCCOMMENT}
1: #!/usr/bin/env -S quint verify --temporal correct
      ^^^

error: parsing failed
```

For reference, Javascript was in a similar situation and recently added hashbang support in ES14 (in 2023):
https://www.w3schools.io/javascript/shebang-examples/

I think there are two alternative ways to implement this:
 1. Adding a new token rule for `#` as another starting marker for single-line comments (similar to `//` and `///`), anywhere in a file.
 2. Adding a custom token rule for `#!` as a new starting marker for an hashbang line, only valid at the beginning of a file.

**Comment by bugarela** [comment]
Oh, I didn't know we could use commands like this in the hasbang! This is awesome. Thanks for reporting, this should be easy to implement as you suggest :)
