### ISSUE TITLE
ITF list of variables does not include variables introduced by the --mbt flag

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/quint#1558]
When `quint run` is called with the `--mbt` flag, it adds two new variables to the ITF trace: `action_taken` and `nondet_picks`. It adds them everywhere, except to the list `vars`. This is where [ITF Trace Viewer](https://marketplace.visualstudio.com/items?itemName=informal.itf-trace-viewer) takes its information on variables. Because the `--mbt`-introduced variables are missing, the trace viewer does not show them.

**Comment by romac** [comment]
While we are at it, I wonder we can ever namespace these variables with `mbt::` or `q::mbt::` to differentiate them (as well as avoid potential clashes) from standard user-defined state variables. Moreover, the Quint docs and APIs typically use `camelCase` identifiers, so perhaps we could also switch to that as well.

**Comment by ivan-gavran** [comment]
> While we are at it, I wonder we can ever namespace these variables with `mbt::` or `q::mbt::` to differentiate them (as well as avoid potential clashes) from standard user-defined state variables. Moreover, the Quint docs and APIs typically use `camelCase` identifiers, so perhaps we could also switch to that as well.

That sounds like a good idea, and I could include it into the draft PR. @bugarela , what do you think?

**Comment by ivan-gavran** [comment]
Closed by #1559
