### ISSUE TITLE
Multiple arity signatures don't have an arity requirement

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#169]
TNT has some multiple arity operators such as `actionAnd` and `match`. Signatures for these operators are parametrized over the number of arguments, but some of them have restrictions over how many arguments it can receive. For example, `match` require an odd number of arguments, while `record` requires an even one. The signature provider needs to check the requested arity against these restrictions before generating a signature.

**Comment by shonfeder** [comment]
I think we got the nub of this in #1078

I'll pick up the special case of `match` in #1082
