### ISSUE TITLE
Recursion check in operator definitions

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#171]
As recursion is not allowed, we should detect recursion in operator and lambda definitions to report them as unsupported. This should be a simple occurs check of the operator's name in its body.

**Comment by konnov** [comment]
I just ran into this issue by typing a wrong name and introducing infinite recursion. The plugin feedback was too complex for me to understand. It would be great to have this fixed :)

**Comment by bugarela** [comment]
Minimal example:
```
module foo {
  val a = a
}
```

I'll wait until the refactor of the lookup system to fix this because this depends too much on it and I will have to completely re-do the check when it changes.

**Comment by konnov** [comment]
Handled by #1008, including the MWE
