### ISSUE TITLE
Centralize mapping of operators parsed from symbols

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#196]
TNT allows some built-in operators to be represented with symbols and then translates them at parsing (i.e. `+` to `iadd`, `{ key: value }` to `rec(key, value)`). These operator names are mostly internal, and they are referenced to in many different parts of the code base (parsing, default definitions for name resolution, effect signatures, type signatures, simulator compiling) which is a problem since we can change the name in some of these places but not others. Also, I keep switching them up (i.e. `rec` vs `record`) so that's annoying.

We should have a single module defining all of those names so we can:
1. Have a single place to update when we want to change them
2. Have static guarantees that we are not referencing an unexisting operator
    - This should also be true for built-in operators in general, not just the ones with symbol representation

**Comment by shonfeder** [comment]
I think the impact of this is not so low anymore. We've hit problems related to this at least thrice this week:

- #815 (missnaming of operator in docs)
- https://github.com/informalsystems/apalache/issues/2530 (no central place for ops, so i overlooked the record ops, which aren't in the builtin sigs.)
- #814 (REPL doesn't handle operator)

**Comment by shonfeder** [comment]
@bugarela I could take this on, if you're not eager for it or don't have the bandwidth :)

**Comment by bugarela** [comment]
Sounds good! I don't think I'll have bandwidth for it this quarter.
