### ISSUE TITLE
VSCode plugin seems to show errors from previous states of buffer

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#214]
The VSCode plugin's syntax errors seem to report errors from previous states of the buffer, not the current state of the buffer. This is true even if the buffer is saved.

I can sync up to show the problem I'm seeing, but I'm not able to capture it in a screen shot (and it's not an issue with the parser, i.e., no error via `tntc parse ...`).

**Comment by bugarela** [comment]
I believe those errors happen when some promises were not properly handled. Recently I made a change where I forgot to handle a promise somewhere, and errors like this started appearing. I fixed it, and they are gone. So I'm closing this as I believe the server and my understanding of it have significantly improved, so I'm relatively confident that this is not happening on stable versions anymore. 

If it happens again, I expect whoever experiences it to either reopen this issue of create a new one.
