### ISSUE TITLE
Support higher-order definitions in the simulator

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#221]
We have to support higher-order definitions at some point:

```
>>> def foo(bar, n) = bar(n)
...
TypeError: Cannot read properties of undefined (reading 'length')
```

It looks like we would need type information for `bar`, in order to produce the right number of registers in the simulator. This calls for integration with the type checker.

@bugarela, are higher-order operators supported by the type checker already?

**Comment by konnov** [comment]
To support higher-order operators in user definitions, we have to know the parameter types. This requires the refactoring planned in #624.

**Comment by konnov** [comment]
We can pass user-defined operators in the built-in operators. I don't think it is a high-impact feature actually.

**Comment by shonfeder** [comment]
I get the same crash trying to apply a named operator in, e.g., a fold:

```
node:internal/readline/emitKeypressEvents:74
            throw err;
            ^

TypeError: Cannot read properties of undefined (reading 'length')
    at CompilerVisitor.applyFold (/apalache/quint/quint/dist/src/runtime/impl/compilerImpl.js:736:49)
    at CompilerVisitor.exitApp (/apalache/quint/quint/dist/src/runtime/impl/compilerImpl.js:439:22)
    at walkExpression (/apalache/quint/quint/dist/src/IRVisitor.js:283:25)
    at walkDefinition (/apalache/quint/quint/dist/src/IRVisitor.js:209:13)
    at /apalache/quint/quint/dist/src/runtime/compile.js:93:71
    at Array.forEach (<anonymous>)
    at /apalache/quint/quint/dist/src/runtime/compile.js:93:25
    at Array.forEach (<anonymous>)
    at compile (/apalache/quint/quint/dist/src/runtime/compile.js:91:26)
    at /apalache/quint/quint/dist/src/runtime/compile.js:145:21
```

i'm wondering if we can make the behavior here, so that, even if hit an unknown unepected corner of the language, repl still doesn't crash?
