### ISSUE TITLE
Support discriminated unions in the type system

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#244]
We need to implement variants and use them to type discriminated unions and their operators (`match`) in the type system.

- [x] Implement type checking and inference for variant construction via the exotic `variant` operator introduced in #1206  
- [ ] Implement type checking and inference for variant elimination via the exotic `match` operator introduced in #1206

**Comment by konnov** [comment]
I also like the approach implemented in `TlaType1` currently, though it may have some quirks we have not had time to think about.
