### ISSUE TITLE
Add `compile` sub command

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#359]
Our current choice of `tntc` commands is dictated by the implementation details, rather than by usability.

Instead of having `parse`, `typecheck`, and maybe something else, I was thinking of introducing the `compile` command:

 - It integrates the full compilation cycle: the parser, the type checker, the effects checker, and (possibly) compilation to JS or TLA+
 - The choice of the compilation target may be give via the `--target` option. The current candidates are: `js` and `json`.
 - For fine-grained control, it introduces options, telling the compiler where to stop, e.g. after parsing, after type checking, etc.

@bugarela, @shonfeder, wdyt?

**Comment by shonfeder** [comment]
Copied over from #1278:

I think I agree with the functionality I'm not sure if I agree on the preferred interface.

The main thing I need is output of the stage that includes flattening, and a compile sub command seems like the right place to put that.

As to whether we should merge the parse and typecheck commands into compile, I'm not so sure. I'm not opposed, I just don't see a problem with having distinct subcommands here or what the benefit is of moving it into flags under a single subcommand. I guess our current interface seems a bit more like cargo than go, in that cargo has both build and check?

**Comment by shonfeder** [comment]
Important additional context and motivation from #1278:

parse and typecheck can be used to check an input's validity for syntax and typechecking, respectively, and to produce the intermediate stage of IR resulting from those processes. However, run, test, verify do not operate on the result of typechecking: instead they all require post-processing that includes forms of flattening and inlining.

This stage of the process is not exposed through the CLI currently, even tho it would be helpful for debugging and is probably what other tooling would want to consume.

I propose exposing this stage of the process through a compile subcommand, which will also become the recommended way for users to perform all static analysis and processing to a spec before passing it off to other tools.

**Comment by konnov** [comment]
Makes sense to me!
