### ISSUE TITLE
Syntax ambiguity in definitions

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#394]
REPL reports an interesting error on the following definition:

```scala
def isPrime(n) = 2.to(n - 1).forall(i => n % i != 0)
syntax error: <input>:1:43 - error: Failed to resolve name n in definition for isPrime, in module __REPL
```

The reason for this error is that the definition is interpreted as an expression, not as a top-level definition. As @bugarela noticed:

```scala
// This is how the REPL is parsing it:
val __input = def isPrime = (n => field(to(2, isub(n, 1)), "forall")) { (i => neq(imod(n, i), 0)) }
// And this is how it should be parsed
def isPrime = (n => forall(to(2, isub(n, 1)), (i => neq(imod(n, i), 0))))
```

There are several factors here:

 1. REPL recognizes the above line as an expression, because I have recently swapped the priorities of expressions and top-level declarations in the grammar:

https://github.com/informalsystems/tnt/blob/38a1d677b90c3fae96554586417ab83fa8c3279e/tntc/src/generated/Tnt.g4#L132

  This was done in #377 to complain about top-level `nondet` declarations, see #378.

 2. Although the above problem appears only in REPL, we could probably write a top-level definition that has exactly the same problematic behavior.

The moment we understand what's going on, there are easy fixes to that:

```scala
// use braces
def isPrime(n) = { [2.to](http://2.to/)(n - 1).forall(i => n % i != 0) }
// use parentheses
def isPrime(n) = (2.to(n - 1).forall(i => n % i != 0))
// use semicolon
def isPrime(n) = 2.to(n - 1).forall(i => n % i != 0);
```

All of the above solutions work. However, I worry that the users will find the initial syntax error counterintuitive and blocking their understanding of the syntax. Perhaps, we should require `{...}` or `(...)` by default. However, this would automatically require another layer of indentation, which is what we wanted to avoid.

**Comment by shonfeder** [comment]
The particular error reported case no longer causes problems with the parser.
