### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/quint#484]
I used `npm i @informalsystems/quint` to install. `$(npm bin)` is on system path. When I try to run `quint`, I get following error,

```
node:internal/modules/cjs/loader:1056
  throw err;
  ^

Error: Cannot find module 'lodash'
Require stack:
- /home/user/node_modules/@informalsystems/quint/dist/src/ToIrListener.js
- /home/user/node_modules/@informalsystems/quint/dist/src/quintParserFrontend.js
- /home/user/node_modules/@informalsystems/quint/dist/src/cliCommands.js
- /home/user/node_modules/@informalsystems/quint/dist/src/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/home/user/node_modules/@informalsystems/quint/dist/src/ToIrListener.js:29:18)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/node_modules/@informalsystems/quint/dist/src/ToIrListener.js',
    '/home/user/node_modules/@informalsystems/quint/dist/src/quintParserFrontend.js',
    '/home/user/node_modules/@informalsystems/quint/dist/src/cliCommands.js',
    '/home/user/node_modules/@informalsystems/quint/dist/src/cli.js'
  ]
}
```

**Comment by shonfeder** [comment]
I was able to reproduce this on a fresh install on a mac. Curious that we haven't seen this earlier!

Thanks for the report!

**Comment by shonfeder** [comment]
We may be hitting this actually https://github.com/npm/npm/issues/17282

**Comment by shonfeder** [comment]
I've just hit the same problem trying to run the vscode extension. @bugarela, perhaps we should cut a new vscode release to pickup #507?

**Comment by shonfeder** [comment]
The (i guess obvious) workaround is just to run

```
npm i lodash
```

in the dir VSCode is putting quints `node_modules` in

**Comment by bugarela** [comment]
I can cut a release today.

**Comment by rnbguy** [comment]
@bugarela can we also have a `npm install` instruction directly from github? `npm i git+https://github.com/informalsystems/quint` would have enough but `package.json` is not present in the repo root. 

So I found [gitpkg](https://gitpkg.vercel.app/), a third party service, which allows `npm i` for a git subrepo. But `npm i 'https://gitpkg.now.sh/informalsystems/quint/quint?main'` doesn't install the `quint` executable in `node_modules/.bin`.

Sure I am doing something wrong. :sweat_smile:

**Comment by bugarela** [comment]
@rnbguy Interesting! I tried it and in deed, it does create a `@informalsystems/quint` folder in `node_modules` but nothing on `.bin`. Maybe @shonfeder will have some idea of what is going on.

**Comment by shonfeder** [comment]
i'll look, but the short of it is that npm doesn't support installing from repos with our structure, and maybe doesn't have great support for that in general, so i'm not sure how far we'll be able to get with that.

**Comment by shonfeder** [comment]
I'll cut a release shortly!

**Comment by shonfeder** [comment]
@bugarela release is out on npm!
