### ISSUE TITLE
Write reference documentation for modes and effects

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#514]
We should give the users basic concepts for modes and effects so they can correctly define their modes, hopefully with the assistant of effect information provided in the plugin.

**Comment by shonfeder** [comment]
Is this different than https://github.com/informalsystems/quint/issues/407 ?

**Comment by bugarela** [comment]
It is not, my bad. Closed in favor of #407

**Comment by shonfeder** [comment]
No worries. We could have closed this one too, as it has a better description.  :) I'll update that with your note.
