### ISSUE TITLE
Module imports and circular imports

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#523]
In the course of #489, I started to write a simple example of bank transfer. Somehow, my coding habits kicked in and I have produced the following code:

```scala
module bank {
  type Addr = str
  // we isolate the keeper interface in a separate namespace
  module keeper {
    // to my surprise, this import works
    // import bank.*
    pure def validateBalance(addr: Addr): bool = {
      true
    }
}
```

There are several points to discuss here:

 - do we want `Addr` to be accessible in `keeper`? I think it is normal behavior in many languages.
 - I can access `Addr` in `keeper` via `bank::Addr`, but is it what we want?
 - Surprisingly, `import bank.*` is working inside `keeper`. It probably leads to circular references in `keeper`.

/cc @bugarela, @shonfeder 

This is probably related to the issue #483 by @lasarojc.

**Comment by bugarela** [comment]
As we don't have nested modules anymore, I believe the only point that still stands here is self-importing. This is the current (weird) behavior

![image](https://user-images.githubusercontent.com/18356186/222804202-874f2a0d-e26a-4670-95c4-5fb7d4a8f586.png)

**Comment by konnov** [comment]
The error message is not explaining much, but it is good that there is an error. How about a cycle like: `B imports A`, `C imports B`, `A imports C`?

**Comment by bugarela** [comment]
>The error message is not explaining much, but it is good that there is an error. How about a cycle like: B imports A, C imports B, A imports C?

This is not possible right now because we require modules to be defined before they are used. Once we implement our topological sort, that itself should be responsible to flag cycles, right?
