### ISSUE TITLE
Implement `instance` for constant expressions

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#528]
It looks like `instance` in general may be too complex to implement #237. However, substituting constants with constant expressions is quite useful, e.g., for testing general protocol specs. We should prioritize this feature, while postponing #237.

It is not clear, at which stage this should be done. It's probably easy to do that at the resolver stage. However, this substitution would require the effects checker.

**Comment by bugarela** [comment]
My idea for this is: at `importResolver`, we replace the `reference` to point to the given expression instead of the constant. In order for the effects to be properly checked, we will have to ensure that `const` definitions always have `Pure` effects (that is, they behave the same as `pure val`).
