### ISSUE TITLE
Handle stateful modules diferently

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#531]
Our language manual describes a behavior that is not yet implemented:

>We distinguish between stateless and stateful modules. A stateful module has at least one constant or variable declaration. All other modules are stateless. This is an important distinction. Definitions of stateless modules may be accessed via the dot-notation and imported, whereas stateful modules must be instantiated before they can be accessed.

**Comment by konnov** [comment]
We have changed our approach to modules. Since we are using imports and exports now, similar to programming languages, this does not seem to be an issue anymore. Hence, I am closing this one.
