### ISSUE TITLE
Reorganize examples

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#563]
Currently, we are dropping new examples into the `examples` directory. Since the directory is getting larger, it is harder to orient there. I received the first feedback already that people had different expectations when looking at the examples. Also, the users may want to look for specific kinds of examples. I am proposing the following structure:

 - `language` for simple examples that demonstrate some basic language features. Now we have plenty of small files right in `./examples`, which is not good.
 - `distributed` for distributed algorithms containing:
   - `LamportMutex`
   - `ClockSync`
   - `Paxos`
   - `ReadersWriters`
   - `ewd840`
   - `tendermint`
 - `cosmos` for cosmos modules, dApps, and smart contracts containing:
   - `ics23`
   - `bank` (currently, in a separate branch)
 - `solidity` for Solidity examples. Although it's not our primary goal to support Solidity, there is a large set of well-scoped Solidity contracts, which could work well as introductory examples. Also, Evmos is using Solidity, so it's related to Cosmos. Currently, we have:
   - `ERC20`
 - `puzzles` for small examples that are good for learning combinatorial behavior of model checkers, though they may be misleading, as combinatorial problems are often harder than e.g. smart contracts. Currently, we have:
   - `tictactoe`
 - `sequential` for sequential algorithms. Again, they are not our primary goal but they may help the users to connect better with the solutions they already know.

@bugarela, @shonfeder, @thpani, @Kukovec, ideas?

**Comment by thpani** [comment]
SGTM.

People with different backgrounds might have different expectations about these categories, so I think more important than the actual directory names is a solid README file to briefly explain these rough categories.

I don't know how much structure we want to impose, but maybe the following provides a bit more guidance?

* `language_features`
* `textbook_algorithms`
  * `sequential`
  * `distributed`
* `blockchain_applications`
  * `cosmos`
  * `solidity`
* `puzzles`

**Comment by bugarela** [comment]
I like it, specially with @thpani's suggestion

**Comment by konnov** [comment]
Yeah, I like the suggestion by Thomas, though we have to understand where Tendermint should fit.
