### ISSUE TITLE
Write Cosmos dapps in Quint

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#565]
Similar to #564, we should be able to collect a set of small examples that mirror example dapps in Cosmos. [Cosmos Developer Portal](https://tutorials.cosmos.network/) looks like a good first step.

**Comment by shonfeder** [comment]
Relevant:

- #586
- #587
- #588

**Comment by shonfeder** [comment]
we have https://github.com/informalsystems/quint/tree/8ff175a9d7b893c3bb9fab6537356b060db9c31b/examples/cosmos/ now.
