### ISSUE TITLE
Replace string literals with identifier literals?

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#570]
I am currently writing an example in Quint. The syntax of `with` is quite distracting:

```scala
            auctionState' =
                as.with("highestBid", value)
                  .with("highestBidder", sender)
                  .with("pendingReturns", newPendingReturns),
```

I think we have discussed this at some point. We are passing a string literal here, as e.g. `highestBid` would be an identifier, and it could be confused with an argument. As we all know, strings are fragile, as it is very easy to make a typo. Would it make sense to replace string literals with identifier literals, e.g., `:highestBid`? In this case, the example would look like:

```scala
            auctionState' =
                as.with(:highestBid, value)
                  .with(:highestBidder, sender)
                  .with(:pendingReturns, newPendingReturns),
```

/cc @shonfeder, @bugarela, @Kukovec, @thpani

**Comment by thpani** [comment]
In favor, but I have two questions 😄 

1. Would it make sense to find a syntax that works uniformly for record type definitions and field access?
If we only introduce this for field access, people could get confused and define their record type more Ruby-esque like:
```ruby
type T = { :highestBid: T_1, :highestBidder: T_2, ..., :pendingReturns: T_n }
```

2. Can we use `:symbol`s as discriminated union tags?

**Comment by bugarela** [comment]
Also in favor! 

> If we only introduce this for field access, people could get confused and define their record type more Ruby-esque like:

Actually, Ruby supports three different syntax for hashes (maps):
```ruby
#1
{ highestBid: value, highestBidder: sender, pendingReturns: newPendingReturns }
#2
{ :highestBid => value, :highestBidder => sender, :pendingReturns => newPendingReturns }
#3
{ "highestBid" => value, "highestBidder" => sender, "pendingReturns" => newPendingReturns }
```

1 and 2 are interchangeable, while 3 is different. My point is: `key:` and `:key =>` mean the same thing, and I'd rather keep our current syntax form for record constructors and teach people that `:key` in `with` stands for the `key:` part of the constructor.

> Can we use :symbols also as discriminated union tags?

We should be able to, but we are also reformulating our representation of variants. See https://github.com/informalsystems/quint/issues/539

**Comment by thpani** [comment]
> My point is: `key:` and `:key =>` mean the same thing, and I'd rather keep our current syntax form for record constructors and teach people that `:key` in `with` stands for the `key:` part of the constructor.

Makes sense!

**Comment by konnov** [comment]
> 1. Would it make sense to find a syntax that works uniformly for record type definitions and field access?

Maybe we could introduce a special syntax for record field updates later. What I notice is that a few Quint operators require field names as string literals, and that is confusing.

**Comment by shonfeder** [comment]
while i ah in general in favor of supporting symbols/atoms, I'm slightly concerned about introducing this quirk: i think it makes our record field update syntax doubly unusual, and the asymmetry Thomas points out may add to confusion for readers.

Here are a few record update syntax examples from other languages:

Rust:

```rust
let newRec = Rec { f: newValue, ..oldRec };
```
 
Elixer:

```elixer
newRec = %{oldRec | t: newValue}
```

OCaml:

```ocaml
let newRec = {oldRec with t = newVale}
````

Something like this would be preferable IMO, if we are gonna change the syntax in any case.

**Comment by konnov** [comment]
Yeah, I like this direction for record updates. Also, we had a discussion in #118.

I still do not see how we could entirely get rid of string literals/atoms/identifiers, e.g., they are used in REPL to pass operator names. In case of REPL, this could be fixed in the future, but not right now.

**Comment by shonfeder** [comment]
is the scope of this issue replacing string literals entirely, or just for record updates?

**Comment by konnov** [comment]
The scope of this issue is replacing string literals entirely. I just used the example of record updates, since it is the most prominent one.

**Comment by shonfeder** [comment]
ah, my mistake.

How would this impact conversion to TLA?

**Comment by konnov** [comment]
It should not impact the conversion to TLA+, as it is only the surface syntax. On the other hand, some TLA+ specs may become incompatible with Quint, e.g., "I have a space" would require some tricks to get translated into an identifier. However, there are very few specs that are actually using spaces or other non-standard characters.

**Comment by konnov** [comment]
If we want to go this way, we have to rename the type from `str` to something else. I like `atom` but that will be quite confusing for Cosmos users. Other options that I see:

 - `ident`, after all it is just an identifer,
 - `name`, may be a bit confusing,
 - `lit` for a literal.

**Comment by konnov** [comment]
or `symbol`, as @shonfeder suggested in the meeting

**Comment by shonfeder** [comment]
The problem around records has been addressed by our record update syntax, and also discussed elsewhere.

Currently or strings just are atoms, if we at some point want to add string operations and introduce a new type for atoms, we can reopen this issue.
