### ISSUE TITLE
Improve REPL color contrast

### ISSUE THREAD

**Issue by thpani** [informalsystems/quint#574]
REPL output is hardly readable with a dark terminal theme:

![Screen Shot 2023-01-27 at 14 16 00](https://user-images.githubusercontent.com/82047/215097256-b02c4506-2605-4bca-a8f1-748fb0d98668.png)

I think the solution would be not to explicitly color delimiters like `,`, `(`, and `)` using `chalk.black` – instead, just use the default foreground terminal color.

**Comment by konnov** [comment]
Great point! I've never tried it with the dark theme. Labelling it as "good first issue", if somebody wants to contribute.

**Comment by HosamIntel** [comment]
May I take this one?

**Comment by konnov** [comment]
Sure, feel free to work on this issue!

**Comment by shonfeder** [comment]
Hi, @HosamIntel! Thanks for your interest in contributing :)

You can check out https://github.com/informalsystems/quint/blob/main/CONTRIBUTING.md#contributing for some general pointers, and please feel free to ask if you have any questions or could use any pointers!
