### ISSUE TITLE
Introduce `ok()` as a counterpart of `fail()`

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#594]
Consider the following test:

```
    run sendWithoutMintTest = {
        init.then(send(minter, "bob", 5))
            .fail()
    }
```

Although this test is expected to fail, we cannot guarantee that it fails only after calling `send(...)`. We have to make sure that `init` goes through, which may be non-trivial to show, as `init` is non-deterministic. We have to add `ok()` that complements `fail()` in tests.

**Comment by konnov** [comment]
Or maybe we introduce `expect(expectedResult)` to avoid proliferation of new operators.

/cc @shonfeder, @thpani, @bugarela, @Kukovec, wdyt?

**Comment by shonfeder** [comment]
I don't think I really understand the proposal. Maybe we can discuss tomorrow of you could show an example of how this would be used.

**Comment by thpani** [comment]
> We have to add `ok()` that complements `fail()` in tests.

I get the technical challenge here, but wouldn't this be rather verbose?

**Comment by konnov** [comment]
This is probably subsumed by #1252
