### ISSUE TITLE
Group error classes in one place

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#631]
I am trying to produce an error in the CLI. Currently, we have at least three error classes introduced in various places:
 
 https://github.com/informalsystems/quint/blob/1d67fb43758aa08195fe1a80e1385328d884f33e/quint/src/quintIr.ts#L26
 https://github.com/informalsystems/quint/blob/1d67fb43758aa08195fe1a80e1385328d884f33e/quint/src/quintError.ts#L18
 https://github.com/informalsystems/quint/blob/1d67fb43758aa08195fe1a80e1385328d884f33e/quint/src/quintParserFrontend.ts#L40

We also have adapter functions, e.g.:

https://github.com/informalsystems/quint/blob/1d67fb43758aa08195fe1a80e1385328d884f33e/quint/src/cliCommands.ts#L147

It's getting harder to navigate across error handling. Shall we group all three classes (if we need all three of them) and their adapters in a single file, e.g., `quintIr.ts`?

@bugarela, @shonfeder, wdyt?

**Comment by bugarela** [comment]
Yep, we should centralize those in `quintError` (`quintIr` would be too flooded with error stuff). There's also `ErrorTree`. We should also ensure we are using `QuintError` to represent errors and `ErrorMessage` should be strictly an output format.
