### ISSUE TITLE
Vintage syntax highlighting

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#636]
Since we have low chances of having Github syntax highlighting for Quint in the near future, we could automatically produce a markdown page that uses the restricted markup. I have managed to produce something that looks like syntax highlighting in the old textbooks. Very vintage :)

**module**&nbsp;HighlightJS&nbsp;**{**
&nbsp;&nbsp;**//**&nbsp;<code>single-line comments</code>
&nbsp;&nbsp;**type**&nbsp;Addr&nbsp;**=**&nbsp;<ins>str</ins>
&nbsp;&nbsp;**pure**&nbsp;**val**&nbsp;MAX_UINT **=** <code>2</code>**^**<code>256</code> **-** <code>1</code>
&nbsp;&nbsp;**const**&nbsp;ADDR:&nbsp;<ins>Set</ins>[Addr]

&nbsp;&nbsp;**action**&nbsp;init:&nbsp;<ins>bool</ins> = {
&nbsp;&nbsp;&nbsp;&nbsp;**nondet**&nbsp;sender&nbsp; = &nbsp;oneOf(ADDR)
&nbsp;&nbsp;&nbsp;&nbsp;**all**&nbsp; {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;balances'&nbsp;**=**&nbsp;ADDR.mapBy(a &gt; <code>0</code>)
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}

&nbsp;&nbsp;**run**&nbsp;mintSendTest&nbsp;=&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;init.then(mint(<code>"alice"</code>, <code>"bob"</code>, <code>10</code>))
&nbsp;&nbsp;}
**}**

**Comment by romac** [comment]
Looks pretty nice indeed!

As an alternative, I wonder how much mileage you could get out of using another language's highlighting for Quint. It may look a bit weird in the Markdown source because of the language mismatch in the code fence block, but perhaps adding an (invisible, HTML) comment before the code block to explain why that is may help.

Quick tests with a few languages off the top of my head:

Scala

```scala
module HighlightJS {
  // single-line comments
  type Addr = str
  pure val MAX_UINT = 2^256 - 1
  const ADDR: Set[Addr]

  action init: bool = {
    nondet sender  =  oneOf(ADDR)
    all  {
      balances' = ADDR.mapBy(a > 0)
    }
  }

  run mintSendTest = {
    init.then(mint("alice", "bob", 10))
  }
}
```

---

Python

```python
module HighlightJS {
  // single-line comments
  type Addr = str
  pure val MAX_UINT = 2^256 - 1
  const ADDR: Set[Addr]

  action init: bool = {
    nondet sender  =  oneOf(ADDR)
    all  {
      balances' = ADDR.mapBy(a > 0)
    }
  }

  run mintSendTest = {
    init.then(mint("alice", "bob", 10))
  }
}
```

---

Haskell

```haskell
module HighlightJS {
  // single-line comments
  type Addr = str
  pure val MAX_UINT = 2^256 - 1
  const ADDR: Set[Addr]

  action init: bool = {
    nondet sender  =  oneOf(ADDR)
    all  {
      balances' = ADDR.mapBy(a > 0)
    }
  }

  run mintSendTest = {
    init.then(mint("alice", "bob", 10))
  }
}
```

---

OCaml


```ocaml
module HighlightJS {
  // single-line comments
  type Addr = str
  pure val MAX_UINT = 2^256 - 1
  const ADDR: Set[Addr]

  action init: bool = {
    nondet sender  =  oneOf(ADDR)
    all  {
      balances' = ADDR.mapBy(a > 0)
    }
  }

  run mintSendTest = {
    init.then(mint("alice", "bob", 10))
  }
}
```

---

TypeScript

```typescript
module HighlightJS {
  // single-line comments
  type Addr = str
  pure val MAX_UINT = 2^256 - 1
  const ADDR: Set[Addr]

  action init: bool = {
    nondet sender  =  oneOf(ADDR)
    all  {
      balances' = ADDR.mapBy(a > 0)
    }
  }

  run mintSendTest = {
    init.then(mint("alice", "bob", 10))
  }
}
```

---

JavaScript

```javascript
module HighlightJS {
  // single-line comments
  type Addr = str
  pure val MAX_UINT = 2^256 - 1
  const ADDR: Set[Addr]

  action init: bool = {
    nondet sender  =  oneOf(ADDR)
    all  {
      balances' = ADDR.mapBy(a > 0)
    }
  }

  run mintSendTest = {
    init.then(mint("alice", "bob", 10))
  }
}
```

---

Java

```java
module HighlightJS {
  // single-line comments
  type Addr = str
  pure val MAX_UINT = 2^256 - 1
  const ADDR: Set[Addr]

  action init: bool = {
    nondet sender  =  oneOf(ADDR)
    all  {
      balances' = ADDR.mapBy(a > 0)
    }
  }

  run mintSendTest = {
    init.then(mint("alice", "bob", 10))
  }
}
```

**Comment by konnov** [comment]
Oh, cool. The OCaml highlighting works almost as expected. It's really pity that Scala breaks on the assignment `x' = ...`. Maybe that's a good argument for getting rid of the primes after all.

**Comment by thpani** [comment]
Yeah, I think I prefer some existing highlighting... the line-spacing in the "vintage" highlighting is really weird 😄 

Until we reach those 200 repos required by Github, I wonder what it would take to hook into GH's highlighting using a browser extension. In principle, the code blob seems to be transmitted in raw and highlighted on the client-side:

```shell
$ curl -s 'https://github.com/.../clockSync3.qnt' -H 'Cookie: _octo=GH...' | \
    grep 'A transl' | jq '.payload.blob.rawBlob'
"// A translation of https://github.com/informalsystems/tla-apalache-workshop/blob/main/examples/clock-sync/ClockSync3.tla\nmodule ClockSync3 {\n
    //// HELPERS\n\n    /// `S.add(e)` is `S.union(Set(e))`, i.e., the set derived by adding `e` to `S`\n..."
```

**Comment by konnov** [comment]
I have not thought of a browser extension! We even have a quickly hacked syntax for [highlight.js](https://github.com/informalsystems/quint/tree/main/editor-plugins/highlight.js). So the only thing the extension should do is to embed the links to CSS and JS.

**Comment by konnov** [comment]
I guess, we could use [tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) to inject highlighting scripts, though I am not sure how many people would be willing to do that in their browser :)

**Comment by konnov** [comment]
There is also [Sight](https://github.com/tsenart/sight), which would require us to add our language in their repo somehow.

**Comment by romac** [comment]
> Oh, cool. The OCaml highlighting works almost as expected. It's really pity that Scala breaks on the assignment `x' = ...`. Maybe that's a good argument for getting rid of the primes after all.

Yeah it's only the comments that look a bit weird, but that's a minor issue imho.

**Comment by konnov** [comment]
actually, OCaml highlighting breaks badly too:

https://github.com/informalsystems/quint/blob/igor/prisoners-example/examples/puzzles/prisoners/prisoners.qnt

**Comment by konnov** [comment]
I made it only to the middle of [this list](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml). Many existing style break on `'`, as suspected. So far, the closest ones are:

 - `c`
 - `als` (Alloy)
 - `bsv` (BlueSpec)
 - `boogie`
 - `icl` (Clean)
 - `fan`

**Comment by shonfeder** [comment]
I think we are ok with bluespec now until we have critical mass to get official support for quint.
