### ISSUE TITLE
Design and plan release and integration with Apalache

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#701]
We'll need a thoughtout policy and practice to ensure the best outcomes w/r/t integration and interoperation with Apalache.

Some options discussed today:

- keep a loose and unreliable coupling, and just let quint break combat with Apalache
- pin quint to specific versions of apalache, and run integration tests against the latest Apalache to catch breackage.
- move development of quint and apalache into a monorepo

Let's maybe use this issue to compile requirements before we settle on an approach and document it in an ADR.

cc/ @konnov and @bugarela 

- [ ] Update CLI docs https://github.com/informalsystems/quint/blob/51aaa638e278f250ab4da9d93756533eaa67c15e/doc/quint.md#L281-L287

**Comment by shonfeder** [comment]
For distributing apalache along-with, or thru quint, we can consider these kinds of utilities:

- https://www.npmjs.com/package/node-jre would let us ensure a JRE is installed
- https://www.npmjs.com/package/jdeploy would us distribute apalache via npm (and we can then add it as a dep in our package manifest)

**Comment by thpani** [comment]
> For distributing apalache along-with, or thru quint, we can consider these kinds of utilities:
> 
>     * https://www.npmjs.com/package/node-jre would let us ensure a JRE is installed

`node-jre` is deprecated, and its successor https://github.com/nvuillam/njre hasn't seen updates in over a year (in particular, it still lacks support for the Apple M1 `arm64` architecture). So these fall flat.
