### ISSUE TITLE
New syntax for imports

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#741]
As discussed in ADR 6, we should allow qualified imports. I was actually thinking we should have 4 alternatives:
```
// 1
import A as MyA
// 2
import A
// 3
import A.*
// 4
import A.name
```

(2) is here so we don't have to do `import A as A` which is too dumb. Here's an example of it's usage from a discussion I had with Lásaro:
```bluespec
module A {
  var x: int
  action init = x' = 1
}

module B {
  var y: int
  action init = y' = 2
}

module C {
  import A
  import B

  action init = all {A::init, B::init}
}
```

Any objections? @shonfeder @konnov

**Comment by shonfeder** [comment]
1-3 make sense to me. If we have 4, I expect people will want a way to import multiple names on line before too long?

`import A.{name1, name2}`

**Comment by shonfeder** [comment]
Oh actually, shouldn’t the import syntax match the reference syntax more closely? So

```
// 3
import A::*
// 4
import A::name

```

WDYT?

**Comment by konnov** [comment]
Looks good to me! Not sure we should embrace importing multiple names. After all, we are in spec writing, specs should be concise.

**Comment by konnov** [comment]
> Oh actually, shouldn’t the import syntax match the reference syntax more closely? So
> 
> ```
> // 3
> import A::*
> // 4
> import A::name
> ```
> 
> WDYT?

I think `import A::name` and `import A::*` is just too surprising. Can we avoid that?

**Comment by bugarela** [comment]
We can postpone importing multiple names since that's sort of independent of the other changes and is non-breaking, so we can add it later.

**Comment by shonfeder** [comment]
IMO, I’d not support importing 
 a single name than either. Qualified imports should be enough. And one can always do:

`val Foo = M::bar`

If renaming is needed

**Comment by shonfeder** [comment]
> think `import A::name` and `import A::*` is just too surprising. Can we avoid that?

Why is it surprising? Isn’t it more surprising to use the record access syntax on imports?

**Comment by bugarela** [comment]
Are you saying we should drop support for (4)?

**Comment by bugarela** [comment]
We do, there are some special cases in the implementation to handle that. If we decide to support `import A.{name1, name2}` at some point, it would be easier if we keep those special cases for now and then adapt them to support sets of names as well.

One point favoring supporting this specialized imports is that it can help with performance a lot. We will copy all of the definitions of a module when the other forms of imports are used. Typecheck all of them, compile all of them... Once we have topological sorting, we can bring only the specific definitions and its dependencies.

We could also think about using topological sort to not copy unused definitions even if the user wrote a general import. Idk.

Let's add (1) and (2) for now and we can re-visit this when looking at the topological dependencies and optimizations. Sounds ok?

**Comment by shonfeder** [comment]
Makes sense to me!
