### ISSUE TITLE
Need to lookup for operator qualifiers

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#747]
When working on #677, I have realized that we have to tell apart names that refer to actions from other names. This is needed to trace actions but not all kinds of other operators, as there may be a lot of calls to user-defined operators. I tried to use the inferred modes, but that's not exactly what is needed. Currently, `lookupTable` refers to a custom data structure:

https://github.com/informalsystems/quint/blob/218fc1b0ad9a6f9621090c3f66d6db925e2bbe93/quint/src/lookupTable.ts#L4-L11

It would be much more convenient, if the lookup table was returned `QuintOpDef`. I believe that `Definition` duplicates `QuintOpDef` to  large extent.

@bugarela, wdyt?

**Comment by bugarela** [comment]
The inferred modes seem a more suitable answer here. The qualifier provided by the user (available at name resolving) might me too general (i.e. all non-temporal operators could be annotated with `action`).

Other than that, it should be totally possible to add the qualifier to `Definition`. I'm just trying to understand if that's really what you need.

**Comment by konnov** [comment]
> The inferred modes seem a more suitable answer here. The qualifier provided by the user (available at name resolving) might me too general (i.e. all non-temporal operators could be annotated with `action`).

I tried that, and modes were a bit too hard to wire. On the other hand, we are already doing a lookup for names.

**Comment by bugarela** [comment]
This was solved a while ago :)
