### ISSUE TITLE
Chains of imports

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#753]
As we expected, the default behavior of exports being non-transitives makes it harder to reuse instances in the chains of imports. The example below by @lasarojc demonstrates the complications with chains of imports that include instances.

Load the example in REPL:

```sh
$ quint -r t.qnt
Quint REPL v0.0.3
Type ".exit" to exit, or ".help" for more information
true
>>> import scratchC.*

>>> B::A::Procs1
Set(1, 2)
>>> B::A::procs0
syntax error: error: Failed to resolve name B::A::procs0 in definition for __input, in module __repl__
B::A::procs0
^^^^^^^^^^^^
>>> import scratchB as B2
>>> B2::init
true
```

What is happening here? Since REPL introduces its own module internally, we have one more hidden import:

```bluespec
module __repl__ {
  import scratchC.*
  // ...
}
```

So the contents of `B` is not visible in `__repl__`, though `B` itself is visible in `__repl__`. I think, the contents of `B` should be actually visible in `__repl__`, since `__repl__` has imported all of `scratchC`.

Related to that, as we discussed earlier, we should probably add the combo `export import`, that transitively propagates imports.

@bugarela, @shonfeder, wdyt?

```bluespec
// t.qnt
module scratchA {
    type Proc = int
    const Procs1: Set[int]
    const Procs2: Set[Proc]
}

module scratchB {
    import scratchA(
        Procs1 = Set(1,2),
        Procs2 = Set(3,4)
    ) as A

    var procs1: Set[A::Proc]
    var procs2: A::Proc -> A::Proc

    action unchangedAll = all {
        procs1' = procs1,
        procs2' = procs2
    }

    action init = all {
        procs1' = A::Procs1,
        procs2' = A::Procs2.mapBy(p => p+1)
    }

    action step =
        unchangedAll
}

module scratchC {
//    import scratchA.*       //Conflicting definitions of Proc and B::Proc
//    import scratchA as A    //A::Procs1 and A::Procs2 are not resolved inside scratchC
    import scratchA(
        Procs1 = Set(5,6),
        Procs2 = Set(7,8)
    ) as A

    import scratchB as B

    var procs3: A::Proc -> Set[A::Proc]

    action unchangedAll = all {
        B::unchangedAll,
        procs3' = procs3
    }

    action init = all {
        B::init,
        procs3' = A::Procs1.mapBy(p => A::Procs2)
    }

    action step =
        unchangedAll
}
```

**Comment by konnov** [comment]
The difference here is that `B` is an instance, so if we import a module with the same parameters in two different modules, we import two different instances (which may disagree on state variables). This is most likely not what people would expect.

**Comment by shonfeder** [comment]
What makes `B` an instance here? I thought instances needed to be instantiated? It "inherits" this from the fact that `scratchA` is an instance?

All that aside, why should `B::A::procs0` be defined? I see no `procs0` in `scratchA`. But both if these work:

```scala
true
>>> import scratchC.*

>>> B::A::Procs1
Set(1, 2)
>>> B::A::Procs2
Set(3, 4)
```

I think I don't understand what problem is being identified here :sweat_smile:

**Comment by lasarojc** [comment]
procs0 was added later. The updated spec is as follows.

```scala
module scratchA {
    type Proc = int
    const Procs1: Set[int]
    const Procs2: Set[Proc]

    var procs0: Set[Proc]

    action unchangedAll = all {
        procs0' = procs0
    }

    action init = all {
        procs0' = Procs1
    }

    action step =
        unchangedAll
}

module scratchB {
    import scratchA(
        Procs1 = Set(1,2),
        Procs2 = Set(3,4)
    ) as A

    var procs1: Set[A::Proc]
    var procs2: A::Proc -> A::Proc

    action unchangedAll = all {
        A::unchangedAll,
        procs1' = procs1,
        procs2' = procs2
    }

    action init = all {
        A::init,
        procs1' = A::Procs1,
        procs2' = A::Procs2.mapBy(p => p+1)
    }

    action step =
        unchangedAll
}

module scratchC {
//    import scratchA.*       //Conflicting definitions of Proc and B::Proc
//    import scratchA as A    //A::Procs1 and A::Procs2 are not resolved inside scratchC
/*    import scratchA(
        Procs1 = Set(5,6),
        Procs2 = Set(7,8)
    ) as A                   //Double definition of Procs1 and Procs2
*/

    //If not importing, then types and variables in A are not accessible.

    import scratchB as B

    var procs3: B::A::Proc -> Set[B::A::Proc]

    action unchangedAll = all {
        B::unchangedAll,
        procs3' = procs3
    }

    action init = all {
        B::init,
        procs3' = B::A::Procs1.mapBy(p => B::A::Procs2)

    }

    action step =
        unchangedAll
}
```

**Comment by shonfeder** [comment]
Until/unless we add support for a reexport functionality, as Igor has suggested,
the way I'd think to fix the spec is like this:

```diff
diff --git a/t.qnt b/t.qnt
index e27c98a..bc9af05 100644
--- a/t.qnt
+++ b/t.qnt
@@ -23,6 +23,11 @@ module scratchB {
         Procs2 = Set(3,4)
     ) as A
 
+    type Proc = A::Proc
+
+    val Procs1 = A::Procs1
+    val Procs2 = A::Procs2
+
     var procs1: Set[A::Proc]
     var procs2: A::Proc -> A::Proc
 
@@ -55,7 +60,9 @@ module scratchC {
 
     import scratchB as B
 
-    var procs3: B::A::Proc -> Set[B::A::Proc]
+    var procs3: B::Proc -> Set[B::Proc]
+    val we_can_now_access_Procs1 = B::Procs1
+    val we_can_now_access_Procs2 = B::Procs2
 
     action unchangedAll = all {
         B::unchangedAll,
```

This typechecks and also matches exactly what my programmer's
intuition leads me to expect w/r/t name visibility and access of types and
values.

If it's common to do this reexporting often, an `include`-like keyword could definitely be helpful as a bit of syntax sugar.

**Comment by konnov** [comment]
Actually, it is not given that imports are not transitive. For instance, python3 apparently introduces imported names in the module namespace and allows to import them further.

**Comment by bugarela** [comment]
Which alternative seem better to y'all? Implement an `export` keywork for [re-exporting like typescript](https://www.typescriptlang.org/docs/handbook/modules.html#re-exports) or always export the imported names? I'm leaning towards the former, since the latter removes the user's ability to implement some sort of real encapsulation.
cc @konnov @shonfeder

**Comment by shonfeder** [comment]
Iirc, That bad behavior or Python has been the source of many hours of needless debugging in my life :)

I also prefer explicit exports.

**Comment by lasarojc** [comment]
I think I am starting to understand why constants are instantiated on a separate file, when running TLC.
What I was trying to do is problematic not just because of the syntax, but because I am trying to implement some sort of inheritance here, instead of composing specs.
Even with this new syntax (Thanks @bugarela ) things will not work well (my fault).
If I am still the only reason you are doing this, please hold on before merging.

**Comment by bugarela** [comment]
We are trying to keep our instances and imports simple and stay away from inheritance, as it is probably too much for spec writing. I believe we have a long way forward on exploring different patterns of composition. For now, I think the `export` construct can be helpful. You're not the only reason for this change, as we agree that always restricting the scopes of imports might be annoying.

**Comment by konnov** [comment]
@lasarojc, perhaps we should make another user interview and try to figure out what you are trying to achieve.
