### ISSUE TITLE
REPL should report an error on a definition when it is called without parameters

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#761]
As reported by @nano-o:

> I have this action `NextRound(v)` in the spec and if I call it without an argument in the REPL I just get `<undefined value>`. Should I get an error instead?

Indeed, REPL should write an error message in this case

**Comment by thpani** [comment]
It would actually be cool if it doesn't just error, but prints the definition.

**Comment by konnov** [comment]
In the latest version, it prints the signature of lambda (without types). But it's true, we could even print the definition itself!

**Comment by bugarela** [comment]
I think it is good enough to print the lambda, that's how I remember many REPLs to work. I'll close this since the original problem is solved.
