### ISSUE TITLE
Implement a command similar to `who` in REPL

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#795]
As mentioned by @lasarojc, it would be great to have a command that behaves similar to [who](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-whos) of IPython.

**Comment by lasarojc** [comment]
On a test failure, the command could be automatically executed to show the state in which the failure happened. Delight points if the output is in the form of a state transaction that can be easily copied and pasted into the REPL :)

**Comment by shonfeder** [comment]
This is a duplicate of #446
