### ISSUE TITLE
Effect checker unpacking(?) propagating wrong effects

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#808]
Minimal example:
```
module test {
  pure def isProperChannelSetup(channelSetup: Set[str]): bool =
    tuples(Set("A", "B", "C"), channelSetup).forall((fromChain, toChain) =>
        Set(toChain, fromChain) == channelSetup
    )
}
```

I'm getting a:
```
error: [QNT200] pure def operators may not interact with state variables, but operator `isProperChannelSetup` performs temporal operations over variables v19,v21. Use temporal instead.
```

The effect for the lambda seems correct (a pure arrow effect), but then the result of the `forall` application results in a `Read & Temporal` effect which is not right.

**Comment by Kukovec** [comment]
Ran into this myself, the minimal definition that hits it is:
```
pure def foo(fn: int -> int): bool = {
        nondet domain = fn.keys()
        tuples(domain, domain).forall((x,y) => fn.get(x) == y)
    }
``` 
Some notes: 
1. if `fn` isn't used in the body of `forall` (e.g. `.forall((x,y) => true)`, there's no issue
2. if `tuples` isn't used (e.g. `domain.forall(x => domain.forall(y => fn.get(x) == y))`), there's no issue
