### ISSUE TITLE
Source of cheatsheet is missing

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#815]
Followup to #663.

We are missing the source of the cheatsheet PDF.

When adding it, we should also 

- add a build target to update the PDF
- fix the name of the record domain operator `field` to the correct `fieldNames` (noted by @lasarojc)

**Comment by konnov** [comment]
The source is not missing but it is available in a proprietary format: https://github.com/informalsystems/quint/blob/main/doc/quint-cheatsheet.key

**Comment by shonfeder** [comment]
How does this get updated?

**Comment by konnov** [comment]
It gets updated via "Save as..." in the keynote. Not nice, but it was the fastest way of producing a nice cheatsheet I could think of.

**Comment by konnov** [comment]
Given that we rarely update the cheatsheet, exploring ways for automatically exporting keynote to pdf is not worth our time
