### ISSUE TITLE
Manage Apalache server

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#823]
To provide a user-friendly API, we would like to have a way for quint to manage the apalache server so users don't have to think about this.

For the immediate term, we can just inform CLI users about how to run the server when a connection cannot be made. But as soon as we expose model checking functionality via the VSCode plugin, we should give the LSP server a way to start and spot the Apalache server.

For the future, perhaps we'll want some sort of interactive console similar to `sbt`, which can be used to manage various parts of the specification lifecycle.

**Comment by thpani** [comment]
Inspiration to gather options:

- bazel runs a [long-lived server process, with an idle timeout](https://bazel.build/run/client-server)
- bloop+metals
- jupyter notebooks
- proof assistants
