### ISSUE TITLE
Nested `pure val` that refers to params caches wrong value

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#843]
Consider the following example:
```
module test {
  def foo(x) = {
    pure val bar = x + 1
    bar
  }

  var t: int

  run aTest = (t' = foo(1)).then(t' = foo(2)).then(all{
    assert(t == 3),
    t' = t,
  })

}
```

The pure value `bar` here refers to `x`, which is parameter to `foo`, so the value for `bar` cannot be cached (since it changes if `x` changes). Currently, it is cached, resulting in this behavior:

```
  test
    1) aTest failed after 1 test(s)

  1 failed

  1) aTest:
      /home/gabriela/projects/quint/examples/test.qnt:10:5 - error: Assertion failed
      10:     assert(t == 3),

    [Frame 0]
    foo(1) => 2

    [Frame 1]
    foo(2) => 2

    Use --seed=0x84c63e40f06ed --match=aTest to repeat.

/home/gabriela/projects/quint/examples/test.qnt:10:5 - error: Assertion failed
10:     assert(t == 3),
        ^^^^^^^^^^^^^^

error: Tests failed
```

see how in `Frame 1`, `foo(2) => 2`, which should be `3`.

PS: I couldn't reproduce this by calling `foo()` in the REPL with different values. The bug appeared only in the simulator.

**Comment by bugarela** [comment]
This is pretty annoying, I'm having to use `val` instead of `pure val` in a lot of places to avoid hitting weird caching.

**Comment by konnov** [comment]
Yeah, I can reproduce it. Let's see whether I can fix it quickly.

**Comment by konnov** [comment]
Oh, it looks like the it was introduced in the recent caching of top-level pure vals in #837. Actually, the code applies to nested `pure val`s too. This is why it is happening.
