### ISSUE TITLE
Bad error message when `pure val` is used in a `pure def`

### ISSUE THREAD

**Issue by lasarojc** [informalsystems/quint#868]
There was an error and I fixed it thanks to the error message, but the second part of the error message `but operator `hasEntry` doesn't read or update any state variable` seems to contradict the first `pure val operators may not interact with state variables`.

> error: [QNT200] pure val operators may not interact with state variables, but operator `hasEntry` doesn't read or update any state variable. Use pure def instead.

**Comment by konnov** [comment]
@bugarela wdyt?

**Comment by bugarela** [comment]
Ah, I think thats the case where `pure val` is used instead of `pure def`, right? I saw this once but forgot to open an issue. We should improve the message for this case.

**Comment by lasarojc** [comment]
Yes, @bugarela. that was the case. I should have included it in the description.
