### ISSUE TITLE
`quint verify` fails on counters.qnt

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#896]
I have tried to run the first real test on the Quint-Apalache integration. First of all, I managed to run the example (after fixing a few things by hand). Amazing 🎉 

I ran `quint verify` as follows:

```bash
$ export APALACHE_DIST=$HOME/devl/apalache/target/universal/apalache-0.30.10-SNAPSHOT/
$ ./bin/apalache-mc server --write-intermediate=true
$ quint verify ../examples/language-features/counters.qnt
```

`quint verify` reports the following error:

```
[unknown location]: An operator with the signature ((Bool) => Bool) cannot be applied to the provided argument of type (() => Bool)
```

**Comment by shonfeder** [comment]
I see the problem: it is that our logic on the quint conversion is not propagating our nullary opeartor tracking between operator definitions.

**Comment by shonfeder** [comment]
We still need to ignore `run` declarations, so reopening.
