### ISSUE TITLE
`<undefined value>` in the REPL when evaluating 

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#924]
Given

```
module Test {
   def condition(f) = {
     Set(1).filter(f)
   }

   def demo = condition(x => x > 0)
}
```

Run with

```
$  echo 'demo' | quint -r Test.qnt::Test
Quint REPL 0.11.1
Type ".exit" to exit, or ".help" for more information
true

>>> demo
<undefined value>
>>> 
```

It does not occur if we inline the operator call like

```
module Test {
   def condition(f) = {
     Set(1).filter(x => x > 0)
   }

   def demo = condition(x => x > 0)
}
```

In general, we should not allow any undefined values to be given to the user. we should check for this at the last possible place and report an internal error if an undefined value would be given.

This was reported by @otrack.

**Comment by shonfeder** [comment]
This is also not occurring with other higher order ops other than `filter` afaict.

**Comment by konnov** [comment]
I have missed the case for `forall`, `exists`, `map`, `filter`, `select`, `mapBy`, which are handled separately from user-defined operators. It needs a bit of careful refactoring to transfer the code from `applyUserDefined`.

**Comment by konnov** [comment]
Interestingly, the following one works as expected. It's kind of similar to Scala here. It really makes me wonder, whether this should be the way of passing higher-order operators. @bugarela, @shonfeder, @thpani, wdyt?

```bluespec
module Test {
   def condition(f) = {
     Set(1).filter(x => f(x))
   }

   val demo = condition(x => x > 0)
}
```

**Comment by thpani** [comment]
I'd still expect that I can just pass `f` to `filter` (as in `Set(1).filter(f)`).

**Comment by bugarela** [comment]
I'm with @thpani here, we should be able to do either `condition(x => x > 0)` and `condition(foo)`.
