### ISSUE TITLE
Add `--main` to `verify`

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#925]
Similar to the [command `run`](https://github.com/informalsystems/quint/blob/main/doc/quint.md#command-run), we should add the option `--main` to [verify](https://github.com/informalsystems/quint/blob/main/doc/quint.md#command-verify). Otherwise, it is impossible to verify a module that is named different from the filename, e.g., [prisoners](https://github.com/informalsystems/quint/blob/main/examples/puzzles/prisoners/prisoners.qnt).

**Comment by konnov** [comment]
@thpani this could be a good simple issue to start with

**Comment by shonfeder** [comment]
I thought we could count on modules being fully flattened before being sent to Apalache? I have to look at the code again to be sure, but I don't think we are doing anything with filenames at all in the conversion from Quint to Apalache...

**Comment by shonfeder** [comment]
So after looking at the plumbing a bit, I don't see anything that would require or benefit from this. In particular, #927 is not related afaict.

**Comment by shonfeder** [comment]
I've been able to move into verification of clock sync. So this won't be necessary.

**Comment by konnov** [comment]
Oh, sorry, I think I was not clear in my issue description, wrote it in a hurry.

Here is what I am doing with `quint run`:

```sh
quint run --main=prisoners3 --invariant=countInv prisoners.qnt
```

Since `prisoners3` is an instance of `prisoners`, which gets flattened, I have to specify `prisoners3` as the main module. As far as I can tell, there is no way to specifying `--main=prisoners3`. It's just an omission on my side, when I was writing the doc. It would be great if I could run something like:

```sh
quint verify --main=prisoners3 --invariant=countInv prisoners.qnt
```
