### ISSUE TITLE
`verify` fails on duplicate `_`

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#926]
The integration fails on [tictactoe.qnt](https://github.com/informalsystems/quint/blob/main/examples/puzzles/tictactoe/tictactoe.qnt):

```sh
quint verify --init=Init --step=Next tictactoe.qnt
```

produces the following error message:

```
error: PASS_FAILURE: {"pass_name":"SanyParser","error_data":"Input was not a valid representation of the QuintIR: Conversion failed while building operator definition QuintOpDef(28,Init,action,QuintApp(27,actionAll,List(QuintApp(11,assign,List(QuintName(10,nextTurn), QuintStr(9,X))), QuintApp(26,assign,List(QuintName(25,board), QuintApp(24,mapBy,List(QuintApp(14,to,List(QuintInt(12,1), QuintInt(13,3))), QuintLambda(23,List(QuintLambdaParameter(15,_)),def,QuintApp(22,mapBy,List(QuintApp(18,to,List(QuintInt(16,1), QuintInt(17,3))), QuintLambda(21,List(QuintLambdaParameter(19,_)),def,QuintStr(20,_))))))))))),None): Variable shadowing in [_ ∈ (1 .. 3) ↦ \"_\"]: _.","exit_code":150}
```

It looks like this is the source of the error:

https://github.com/informalsystems/quint/blob/a30e1fc98e09714ce22962efb460befc015ccb12/examples/puzzles/tictactoe/tictactoe.qnt#L9

**Comment by shonfeder** [comment]
Can the quint IR generate unique variable names for the `_`? That would fix the problem iiuc without us needing extra logic on the Apalache side. WDYT? (cc @bugarela )

**Comment by konnov** [comment]
> We could maybe have a data structure for quint names (instead of using strings) with something like `{ kind: 'name', name: string } | { kind: 'underscore'}`

Is it conceptually different from having what we have already: `{ kind: 'name', name: string }`. The object `{ kind: 'name', name: '_' }` is the special case that would correspond to `{ kind: 'underscore' }`.

**Comment by thpani** [comment]
This was fixed by https://github.com/informalsystems/apalache/pull/2608.

`tictactoe` still fails due to #966
