### ISSUE TITLE
Code 150 on verify clockSync3

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#927]
This is probably related to #925. I run the integration on `clockSync3.qnt`:

```
quint verify --init=Init --step=Next clockSync3.qnt
```

The server is returning:

```
error: PASS_FAILURE: {"pass_name":"SanyParser","error_data":"Input was not a valid representation of the QuintIR: expected sequence got dictionary","exit_code":150}
```

I suspect that this is due to the main module being called `ClockSync3`, not `clockSync3`.

**Comment by shonfeder** [comment]
@konnov could you explain your hunch about module names a bit? I wouldn't expect that, but I'm not exactly sure yet what is causing this, so any tips would be helpful :D

**Comment by shonfeder** [comment]
I think this is a serialization error due the representation of type annotations on operator defs.
