### ISSUE TITLE
REPL returns `<undefined value>` instead of failing, when picking from maps with unbounded (`Int`) codomains

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/quint#954]
```
val m = setOfMaps(1.to(5), Int)
```
fails with `Error: Infinite set Int is non-enumerable`, as expected, however

```
var x: int
  
action foo = {
    nondet y = oneOf(setOfMaps(1.to(5), Int))
    x' = y.get(1)
}
```

returns `<undefined value>` when attempting to execute `foo`.

**Comment by konnov** [comment]
I thought that it was easier to fix in the simulator. It is definitely fixable, but not as easy as I expected.
