### ISSUE TITLE
Typechecker infers too generic parameter type

### ISSUE THREAD

**Issue by thpani** [informalsystems/quint#966]
The typechecker seems to compute a too generic parameter type on the tictactoe example:

https://github.com/informalsystems/quint/blob/ca49fa79feba6e59610e0b890cfd008f105b7548/examples/puzzles/tictactoe/tictactoe.qnt#L15-L25

The type for `Move` is computed as `(str, (int, int | r0)) => bool`, but `MoveToEmpty` is `a => bool`.

**Comment by bugarela** [comment]
MRE:

```
module test {
  action MoveToEmpty(player) =
    pure val coordinates = 1
    player == "x"
}
```

seems like something lost going out of the let scope
