### ISSUE TITLE
Display the evaluation stack for nullary operators

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#982]
This unexpected behavior appeared during the first Quint workshop. In the session below, execution stack is not shown when a nullary operator `step` is evaluated, in contrast to unary operators `inc` and `dec`:

```bluespec
$ quint   
Quint REPL 0.11.3
Type ".exit" to exit, or ".help" for more information
>>> var x: int

>>> action inc(i) = x' = x + i

>>> action step = inc(2)

>>> .verbosity=4
.verbosity=4
>>> x' = 0
true

[Frame 0]
q::input() => true

>>> step
true

[Frame 0]
q::input() => true

>>> inc(5)
true

[Frame 0]
q::input() => true
└─ inc(5) => true

>>> x
7

[Frame 0]
q::input() => 7

>>> action dec(i) = all { x - i > 0, x' = x - i }

>>> dec(3)
true

[Frame 0]
q::input() => true
└─ dec(3) => true

>>> dec(10)
false

[Frame 0]
q::input() => false
└─ dec(10) => false

>>>
```

**Comment by konnov** [comment]
I think it is a regression too, @bugarela. Just checked it against 0.11.2.

The problem is that the compiler uses an older execution listener:

https://github.com/informalsystems/quint/blob/81f70ad19b5dbf91551988a1cdd91c47f43b48ae/quint/src/runtime/impl/compilerImpl.ts#L244-L246

Shall we include the evaluation listener in the evaluation context?

**Comment by bugarela** [comment]
Yes, sounds about right. @konnov Do you intend to do this or should I? I can do it tomorrow

**Comment by konnov** [comment]
> Yes, sounds about right. @konnov Do you intend to do this or should I? I can do it tomorrow

Let me check, whether I could quickly fix this

**Comment by konnov** [comment]
In the end, it's a combination of factors. Once I have fixed the behavior introduced by refactoring, another bug surfaced, which was living in the code for much longer.
